### ISSUE TITLE
protoparse: issues parsing some (nested?) annotation

### ISSUE THREAD

**Issue by srenatus** [jhump/protoreflect#108]
Hi!

Thanks for protoreflect, it's a super nice and helpful project.

I've just run into a problem using `protoparse` and a custom annotation we've got. A reproduction case is this:

```go
package main

import (
	"fmt"
	"os"

	"github.com/jhump/protoreflect/desc/protoparse"
)

func main() {
	// this parses the .proto files from disk
	parser := protoparse.Parser{
		ImportPaths: []string{
			".",
			"/Users/stephan/Go/src/github.com/lyft/protoc-gen-validate", # needed, this contains validate/validate.proto, which is imported
		},
	}
	fds, err := parser.ParseFiles(os.Args[1:]...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse proto files %v: %s", os.Args, err)
	}
	fmt.Println(fds)
}
```

and the proto file
```proto3
syntax = "proto3";
package tests.kitchensink;

import "validate/validate.proto";

message String {
    string pattern  = 10 [(validate.rules) = {string: {pattern: "foo+(ba+r)?"}}];
}
```

running `go run test.go string.proto` gives me
```
string.proto:7:47: syntax error: unexpected _STRING, expecting _NAME or '}' or ',' or '['[]
```

(_using_ that proto file with protoc-gen-validate works, though, so I suspect something missing in protoparse's grammer?)

Any hints? Happy to contribute, but I'd need some pointer on where to start....

Thanks!

**Comment by srenatus** [comment]
Btw, the example is contrived, I'm aware of this. These two variants work,
```
string pattern  = 10 [(validate.rules).string.pattern = "foo+(ba+r)?"}}];
string pattern  = 10 [(validate.rules).string = { pattern: "foo+(ba+r)?"}}];
```

but when using this on a `repeated` field, and combining it with `min_items`, I haven't found any applicable alternative, see for example:

```proto3
    repeated string foos = 1
      [(validate.rules).repeated = {
        min_items: 1,
        items: { string: { pattern: "^SOME RE$" } },
       }];
```

**Comment by jhump** [comment]
It's an issue in the grammar. `string` is also a keyword for the eponymous scalar type. I had addressed this in the part of the grammar for defining field names. But apparently, it remains an issue in the part of the grammar for referring to field names in aggregate values.

I think the solution is trivial -- though any change to the grammar could unfortunately result in material parse conflicts. (I think the grammar already has a number of conflicts that are not issues in practice. If this adds add'l conflicts, good tests would be required to make sure the conflict is handled correctly by the generated parser.)

The solution would be to use the `name` symbol, not `_NAME`, in the `aggName` production rule: https://github.com/jhump/protoreflect/blob/master/desc/protoparse/proto.y#L360

**Comment by jhump** [comment]
If you want to try it out and get it working, feel free to submit a PR. Otherwise, I can probably fix this sometime this week.

**Comment by srenatus** [comment]
@jhump I only got a brief look in today. What it revealed is that this seems a bit over my head. How does `proto.y` become `proto.y.go`? (In other words: I'd appreciate if you took over 😉)

**Comment by jhump** [comment]
@srenatus, no problem at all. I looked at it today and made a PR: #111

The fix is really one line in the `proto.y` file, plus the resulting generated gunk in `proto.y.go`. But the PR is a lot bigger because it adds a lot of test cases to the example proto files that the `protoparse` tests use (including a case that exhibits this bug).

BTW, sorry there are no directions for re-generating the yacc parser from `proto.y`. I need to add a `Makefile` or maybe just add more details to READMEs or Go doc.

For posterity, you do this:

```bash
# make sure goyacc is installed
go install golang.org/x/tools/cmd/goyacc

# the parser.go file has a go:generate directive that uses
# goyacc to re-create proto.y.go
go generate -v github.com/jhump/protoreflect/desc/protoparse
```

**Comment by srenatus** [comment]
@jhump thanks for fixing this and sharing your notes. Somehow, my issue seems to persist, though, so I might have messed up my minimally working example above. The concrete message field annotation *still* causing me trouble is
```proto
message IsAuthorizedReq {
    repeated string subjects = 1
      [(validate.rules).repeated = {
        min_items: 1,
        // TODO: something
        items: { string: { pattern: "^(?:(?:team:(?:local|ldap))|user):[[:alnum:]_-]+$" } },
       }];  // line 45
    // some more fields
}
```
protoparse'ing this gives:
```
authz.proto:45:8: syntax error: unexpected '}'
```
I've annotated line 45 in the snipped above (by a comment that isn't in the file, but doesn't change the behaviour).

Can you spot the issue? 😃

**Comment by jhump** [comment]
You've got a trailing comma on the previous line (line 44).

Does `protoc` process this file? If so, I may need to change the grammar again to allow them.

**Comment by srenatus** [comment]
Oh!! Wow, I hadn't noticed. Yeah, this was running through `protoc` without any issues.

**Comment by srenatus** [comment]
Hmm removing the comma (in the line with `items:`) doesn't seem to _really_ help:
```
authz.proto:44:18: syntax error: unexpected _STRING, expecting _NAME or '}' or ',' or '['
```

although the line has changed now 🤔

**Comment by jhump** [comment]
@srenatus, are you sure you are working with the latest source? That error is exactly what my patch should have fixed. I'll investigate, too (and also fix that trailing comma thing).

**Comment by srenatus** [comment]
Shoot, yeah, surely this is right. Botched up a rebase and reverted the update... Trying again now, with revision cc4400ed5be75c897955f2b15a9f95cacea62f46 of `protoreflect`, and no trailing comma: ✅ 

Thank you very much for your help 😃

**Comment by jhump** [comment]
I just pushed a patch to allow trailing commas, to match protoc behavior: #112. I'll merge it soon.

**Comment by srenatus** [comment]
@jhump Thank you! 🎉 🎈
