### ISSUE TITLE
protoparse: SourceCodeInfo is missing in all descriptors

### ISSUE THREAD

**Issue by vadimi** [jhump/protoreflect#160]
After parsing proto files none of the descriptors (services, methods, fields, etc) have `SourceCodeInfo`, i.e. `.GetSourceInfo()` returns `nil`. I looked through the parser code and it seems like sourceCodeInfo parsing  (`generateSourceCodeInfo` method) happens after files linking, which is too late, since all descriptors are already created.

**Comment by jhump** [comment]
Can you provide a reproducer? There are tests that verify this functionality works, and the tests all pass. So perhaps there is something else a miss?

> I looked through the parser code and it seems like sourceCodeInfo parsing (generateSourceCodeInfo method) happens after files linking, which is too late, since all descriptors are already created.

It is not too late: the descriptors are not immutable. After linking, the logic modifies the underlying descriptors to add the source code info. It's done later to avoid doing superfluous work in the event there are link errors.

**Comment by vadimi** [comment]
@jhump I added a test in PR #162 that demonstrates my use case - I'm trying to get comments from service, message, field, etc. The test fails because `msg.GetSourceInfo()` returns `nil`

**Comment by jhump** [comment]
I see the issue. You were right; I was wrong. Sorry about that. My existing test cases (and places where I have personally used this package and needed to extract source code info) was looking directly at the descriptor proto, not the `desc.Descriptor` wrapper. I forgot that had its own accessor for an element's source info. And you're right that the source info needs to be present before linking in order for the wrapper to access it.

**Comment by vadimi** [comment]
ok, thanks for looking into it.
