### ISSUE TITLE
desc/builder: custom options aren't properly resolved and are missing from built files' imports

### ISSUE THREAD

**Issue by noahdietz** [jhump/protoreflect#174]
First of all, thanks for the package, it's been really useful for tool development!

I am using the desc/builder and desc/protoprint pkgs to generate a new proto file containing a service. I set a custom option for the service using similar code I see in the [tests](https://github.com/jhump/protoreflect/blob/master/dynamic/msgregistry/message_registry_test.go#L609-L613). But the printed proto file **doesn't contain the custom service option**. After looking through all of the tests, I'm guessing I'm doing something wrong, because it looks like there is protoprint test output containing service options.

I did a lot of print debugging and saw the custom option being passed around at various stages. I was able to get the option included in the printed proto file by making a change to the protoprint code [here](https://github.com/jhump/protoreflect/blob/master/desc/protoprint/print.go#L1586), adding `dm.GetKnownExtensions()` to the list of `FieldDescriptors` in the range. So that becomes:
```go
for _, fldset := range [][]*desc.FieldDescriptor{md.GetFields(), mf.GetExtensionRegistry().AllExtensionsForType(md.GetFullyQualifiedName()), dm.GetKnownExtensions()} {
```

Any thoughts? Thanks in advance!

My code for adding a ServiceOption is:
```go
opts := &descriptor.ServiceOptions{}
if err := proto.SetExtension(opts, annotations.E_DefaultHost, proto.String(host)); err != nil {
    return nil, nil, err
}

// srv is a ServiceBuilder here
srv.SetOptions(opts)
```

**Comment by noahdietz** [comment]
I could be totally misunderstanding things, but I changed the protoprint tests to have the same custom option injected into the Service (if one was present) using the same code above (`proto.SetExtension` on the reference provided by `GetServiceOptions()` if present). I assumed the test actual output would differ from the golden as a result and fail the tests. This did not happen. Granted, this is a slightly different scenario, using a parsed protoset (tests) rather than one built via the builder pkg (my code).  Lmk if I'm off-base or doing something wrong here. Thanks

**Comment by jhump** [comment]
@noahdietz, the problem is actually in the `desc/builder` package: when you build a descriptor for the service, it is failing to add that option's file to the imports of the service's enclosing file. So, since the file does not import that option, the printer has no knowledge of it.

**Comment by noahdietz** [comment]
Ah ok thanks @jhump for looking into and clarifying the issue. I'm guessing this issue might apply to all other option types (MethodOptions, FieldOptions, etc.) as well then?

**Comment by jhump** [comment]
> I'm guessing this issue might apply to all other option types (MethodOptions, FieldOptions, etc.) as well then?

Yep. I'm looking at fixing it now: there are some tricks to interacting with options -- mainly if a descriptor has custom options that are *not* compiled into the Go program, in which case an extension registry is required. I think that will require some new API, to set an extension registry on a builder (or perhaps to supply one during the call to `Build`).

**Comment by jhump** [comment]
@noahdietz, if you are able to give this a whirl, fetch latest and checkout the branch named 
[jh/builders-should-add-deps-for-options](https://github.com/jhump/protoreflect/compare/jh/builders-should-add-deps-for-options).

I think that will fix the issue you are encountering. In the meantime, I need to write some add'l test cases for this.

**Comment by noahdietz** [comment]
Worked like a charm!

Really appreciate the quick turn around.

**Comment by noahdietz** [comment]
@jhump  out of curiosity, do you plan on making a release soon? I'm pinned to 1.1.0 currently, just wondering what to expect. Thanks

**Comment by noahdietz** [comment]
Thank you! Much appreciated
