### ISSUE TITLE
How can i get recursived json Object from proto files ?

### ISSUE THREAD

**Issue by ShabbyHouse** [jhump/protoreflect#187]

**Comment by ShabbyHouse** [comment]
my question is get json from proto files, what i have done is this:
        
	fds, err := protoparse.Parser{ImportPaths: []string{protoPath}}.ParseFiles(protoFilePath)
	if err != nil {
		println(err.Error())
	}
	fd := fds[0]
	var targetDesc *desc.MessageDescriptor
	for _, msg := range fd.GetMessageTypes() {
		if msg.GetName() == msgName {
			targetDesc = msg
		}
	}
	m := jsonpb.Marshaler{EmitDefaults: true}
	var a bytes.Buffer
	m.Marshal(&a, desc.AsProto())
	println(string(a.String()))
	dmsg := dynamic.NewMessage(desc)
	var b bytes.Buffer
	m.Marshal(&b, dmsg)
        print(string(b))


================================
but the question is : if the message has message filed, 
i get the json just like this:{"a":"a-value","b":null}
but indeed, b like this {"b-key":"b-value","b1-key":"b1-value"}
so, i really need is like this:
{"a":"a-value","b":{"b-key":"b-value","b1-key":"b1-value"}}

how can i do , i don't know weather i describe it clearly, for help~~

**Comment by ShabbyHouse** [comment]
@Joshua Humphries for some help

**Comment by jhump** [comment]
Your example code is confusing. In the problem statement, it sounds like you're telling me that one of the fields (`b`) is emitting `null` in JSON, but you expect it to instead emit some message structure.

However, the example code doesn't do anything of the sort. It just prints a descriptor proto and then prints an empty message whose type is that of the descriptor proto.

Could you include some real code with expected vs. actual output? For example, maybe you're doing something with the dynamic message before converting to JSON (e.g. not just emitting an empty message)? Also, perhaps include the actual `*.proto` source that you are parsing?

**Comment by ShabbyHouse** [comment]
@jhump first of all, thank you for your response.
my question is just like this:
for example, this is my proto file:

syntax = "proto2";
message Person
{
 required string name = 1;
 required int32 id = 2;
 optional string email = 3;
}


message Student
{
  required string name = 1;
  required int32 id = 2;
  optional string email = 3;
  required Person person = 4;
}



and i want to get the json for the message Student:

{
    "name":"",
    "id":0,
    "email":"",
    "person":{
        "name":"",
        "id":0,
        "email":""
    }
}

but for the methods provided, i got the json just like this:
{
    "name":"",
    "id":0,
    "email":"",
    "person":null
}


there is some restriction：there are only proto files and message name provided.

**Comment by jhump** [comment]
@ShabbyHouse, I still don't really understand. What does your Go code look like that is populating the message? If you are seeing `null` for the nested message, I suspect you're not setting that field correctly.

**Comment by sonatard** [comment]
@ShabbyHouse You should allocate memory of message object recursively.

Today I got a same problem, and then write following code.

https://github.com/sonatard/proto-to-postman/blob/master/api_param.go#L112
https://github.com/sonatard/proto-to-postman/blob/master/pbdesc/pbdesc.go#L33

```go
fds, err := protoparse.Parser{ImportPaths: []string{protoPath}}.ParseFiles(protoFilePath)
if err != nil {
	println(err.Error())
}
fd := fds[0]

msgType := fd.FindMessage(msgName)
msg := NewMessage(msgType)

b, err := msg.MarshalJSON()
print(string(b))

func NewMessage(baseMsgType *desc.MessageDescriptor) (*dynamic.Message, error) {
	base := dynamic.NewMessage(baseMsgType)

	for _, field := range baseMsgType.GetFields() {
		if field.GetType() == descriptor.FieldDescriptorProto_TYPE_MESSAGE {
			fieldMsgType := field.GetMessageType()
			msg, err := f.NewMessage(fieldMsgType)
			if err != nil {
				return nil, err
			}

			if err := base.TrySetField(field, msg); err != nil {
				return nil, err
			}
		}

	}

	return base, nil
}
```

**Comment by jhump** [comment]
@ShabbyHouse, if you still can't get things working, feel free to re-open this issue and include more details in reply to my last questions.
