### ISSUE TITLE
Question : How to make grpcreflect.Client's descriptor cache map work?

### ISSUE THREAD

**Issue by CassiaRota** [jhump/protoreflect#191]
I want to use reflect client in http handler as gateway, but it always invoke server twice in one request. First for resolve descriptor , and second for invoke method. It's quite a waste of resources. Such as in grpcurl :
```
 // get conn
    conn, err := gateway.NewGRPCConnection(cmd.Context, opt.Addr, true)
    if err != nil {
        return "",err
    }
    defer conn.Close()
    // get client
    cmd.Client = gateway.NewServerReflectionClient(ctx, conn)
    // get stub
    cmd.Stub = grpcdynamic.NewStub(conn)
    // resolve method
    method, err := cmd.resolveMethod(opt.FullMethodName)
    if err != nil {
        return "",fmt.Errorf("resolve method failed : %s", err.Error())
    }
    // resolve message
    message, err := cmd.resolveMessage(method, opt.Json)
    // resolve headers
    ctx = metadata.NewOutgoingContext(ctx, buildOutgoingMetadata(opt.Headers))
    var headerMD metadata.MD
    var trailerMD metadata.MD
    // invoke
    resp, err := cmd.Stub.InvokeRpc(ctx, method, message, grpc.Header(&headerMD), grpc.Trailer(&trailerMD))
```
 I find client cached `FileDescriptor` In `Client.ResolveService() `,but I should create a client for each request, so client can't get cached in another request. Then how to make `grpcreflect.Client` descriptor map work?Should I cache descriptor manully or held a client for each request?

**Comment by jhump** [comment]
@CassiaRota, the `grpcreflect.Client` is thread-safe. So if you know the target server to dial early, just dial it early and keep/re-use the client for all incoming requests. That way the file descriptors will be cached on first request and then re-used for all subsequent requests.

If you need the cache to be periodically flushed (for example, so it is responsive to new RPC schemas in the event that the server is updated/re-deployed), you'll need to manage your own caching logic around the `grpcreflect.Client`. You could periodically re-create it (effectively getting rid of any cached descriptors the previous instance held). You'd obviously need to make sure the wrapper that re-creates clients is thread-safe so it can be shared by concurrent requests. BTW, you shouldn't ever need to create a new gRPC connection: you should be able to dial the target service once, like at app startup, and then use that for the duration of the process.

**Comment by CassiaRota** [comment]
> @CassiaRota, the `grpcreflect.Client` is thread-safe. So if you know the target server to dial early, just dial it early and keep/re-use the client for all incoming requests. That way the file descriptors will be cached on first request and then re-used for all subsequent requests.
> 
> If you need the cache to be periodically flushed (for example, so it is responsive to new RPC schemas in the event that the server is updated/re-deployed), you'll need to manage your own caching logic around the `grpcreflect.Client`. You could periodically re-create it (effectively getting rid of any cached descriptors the previous instance held). You'd obviously need to make sure the wrapper that re-creates clients is thread-safe so it can be shared by concurrent requests. BTW, you shouldn't ever need to create a new gRPC connection: you should be able to dial the target service once, like at app startup, and then use that for the duration of the process.



> @CassiaRota, the `grpcreflect.Client` is thread-safe. So if you know the target server to dial early, just dial it early and keep/re-use the client for all incoming requests. That way the file descriptors will be cached on first request and then re-used for all subsequent requests.
> 
> If you need the cache to be periodically flushed (for example, so it is responsive to new RPC schemas in the event that the server is updated/re-deployed), you'll need to manage your own caching logic around the `grpcreflect.Client`. You could periodically re-create it (effectively getting rid of any cached descriptors the previous instance held). You'd obviously need to make sure the wrapper that re-creates clients is thread-safe so it can be shared by concurrent requests. BTW, you shouldn't ever need to create a new gRPC connection: you should be able to dial the target service once, like at app startup, and then use that for the duration of the process.

**Comment by CassiaRota** [comment]
> @CassiaRota, the `grpcreflect.Client` is thread-safe. So if you know the target server to dial early, just dial it early and keep/re-use the client for all incoming requests. That way the file descriptors will be cached on first request and then re-used for all subsequent requests.
> 
> If you need the cache to be periodically flushed (for example, so it is responsive to new RPC schemas in the event that the server is updated/re-deployed), you'll need to manage your own caching logic around the `grpcreflect.Client`. You could periodically re-create it (effectively getting rid of any cached descriptors the previous instance held). You'd obviously need to make sure the wrapper that re-creates clients is thread-safe so it can be shared by concurrent requests. BTW, you shouldn't ever need to create a new gRPC connection: you should be able to dial the target service once, like at app startup, and then use that for the duration of the process.

Thanks so much!
