### ISSUE TITLE
[Feature Request] Ability to parse Protobuf descriptors from `string` or `[]byte`

### ISSUE THREAD

**Issue by richardartoul** [jhump/protoreflect#197]
Hello!

I was wondering if it would be difficult to support the ability to parse a `.proto` file that is already stored in a `string` or `[]byte`. The current APIs only support parsing descriptors if they're on the filesystem.

Happy to do the work, just want to get alignment from you on whether you would be ok with that and how difficult that task would be.

**Comment by richardartoul** [comment]
Ah never mind, I see this is a show of #184

**Comment by jhump** [comment]
@richardartoul, I tried to make the API very extensible for cases like this. But I'll be the first to admit that it's not very straight-forward. So I feel like there is a TODO for me in here about adding examples to the package doc.

FWIW, there is now a helper method to simplify this a bit: https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#FileContentsFromMap
