### ISSUE TITLE
[Feature Request]  Keep comment for file descriptor

### ISSUE THREAD

**Issue by ZhiruiLi** [jhump/protoreflect#215]
Sometimes we need comments at top of a file, such as:

```protobuf
// comment1
// comment2
syntax = "proto3";

message M {}
```

But we can't get the header comments now, as the source info of file descriptor is nil. Is it possible to add something like `SyntaxDescriptor` in file descriptor so that we can get the header comment through that? Or just let file descriptor contains source info?

**Comment by jhump** [comment]
@ZhiruiLi, it isn't safe to assume they are syntax comments because the syntax line is optional. The file header you're after will just be the leading comments (possibly just the detached leading comments) of the first element in the file. Because that definition is so imprecise, it's hard to provide an API that will provide something meaningful in all cases. Also, it's unclear how to attribute detached comments -- some comments might be more appropriately attributed to the syntax line (or whatever is the first element in the file), not the file header.

You could instead write your own helper method to go for a "best guess", and the existing API does provide what you need for that:

```go
func fileHeader(fd *desc.FileDescriptor) string {
	var firstLoc *descriptor.SourceCodeInfo_Location
	var firstSpan int64
	for _, curr := range fd.AsFileDescriptorProto().GetSourceCodeInfo().GetLocation() {
		if curr.LeadingComments == nil && len(curr.LeadingDetachedComments) == 0 {
			// skip locations that have no comments
			continue
		}
		currSpan := asPos(curr.Span)
		if firstLoc == nil || currSpan < firstSpan {
			firstLoc = curr
			firstSpan = currSpan
		}
	}
	if firstLoc == nil {
		return ""
	}
	if len(firstLoc.LeadingDetachedComments) > 0 {
		return strings.Join(firstLoc.LeadingDetachedComments, "\n")
	}
	return firstLoc.GetLeadingComments()
}

func asPos(span []int32) int64 {
	return (int64(span[0]) << 32) + int64(span[1])
}
```

**Comment by ZhiruiLi** [comment]
Thanks, that’s a good workaround.

**Comment by mingzhi** [comment]
@jhump, will your code snippet pick the wrong file comments in the following case:
```
syntax "proto3";

// This is not the file header, but it may be picked up by the function fileHandle
message M {}
```

**Comment by jhump** [comment]
@mingzhi, it would. To fix that, you could further inspect the path of the source location and disregard comments that were associated with other descriptors (like messages in your case).

A likely correct step is to only consider ones that are attributed to the syntax declaration, package declaration, an option, or an import. These would be paths that start with 12, 2, 8, and 3 (respectively). Any other path would correspond to some other descriptor or to declarations _inside_ some other descriptor.

**Comment by lukesneeringer** [comment]
I _think_ that makes the corrected function the following:

```go
func fileHeader(fd *desc.FileDescriptor) string {
	var firstLoc *descriptor.SourceCodeInfo_Location
	var firstSpan int64
	for _, curr := range fd.AsFileDescriptorProto().GetSourceCodeInfo().GetLocation() {
		// Skip locations that have no comments.
		if curr.LeadingComments == nil && len(curr.LeadingDetachedComments) == 0 {
			continue
		}
		// Skip locations that are not syntax, package, option, or import.
		allowedPaths := map[int32]struct{}{2: {}, 3: {}, 8: {}, 12: {}}
		if _, ok := allowedPaths[curr.GetPath()[0]]; !ok {
			continue
		}
		currSpan := asPos(curr.Span)
		if firstLoc == nil || currSpan < firstSpan {
			firstLoc = curr
			firstSpan = currSpan
		}
	}
	if firstLoc == nil {
		return ""
	}
	if len(firstLoc.LeadingDetachedComments) > 0 {
		return strings.Join(firstLoc.LeadingDetachedComments, "\n")
	}
	return firstLoc.GetLeadingComments()
}

func asPos(span []int32) int64 {
	return (int64(span[0]) << 32) + int64(span[1])
}
```

Corrections welcome if I got it wrong. (If it is right, perhaps update the original comment?)

**Comment by jhump** [comment]
@lukesneeringer, that looks right. Updated. Thanks.

**Comment by mingzhi** [comment]
Nitpick: I think the for loop should break once we reach an element other than syntax, import, package, or options.

**Comment by mingzhi** [comment]
If the locations are not guaranteed to be sorted, please discard my last comment.
