### ISSUE TITLE
CreateFileDescriptorFromSet ignore other messages in file descriptor set

### ISSUE THREAD

**Issue by Tochemey** [jhump/protoreflect#244]
Hello,

I have a file descriptor set generated by prototool that contains a lot of messages. Even when I run the following command:
`
prototool descriptor-set path/to/proto --json | \
  jq '.file[] | select(.messageType != null) | .messageType[] | .name' | \
  sort | uniq
` on the proto definitions directory I could see all the messages. However when I call in the code: `fd, err := desc.CreateFileDescriptorFromSet(fileDescriptorSet)` I only get two messages which is absurd.

The file descriptor set contains all the descriptors for all the proto messages in the directory per the info I got from prototool site : [prototool](https://github.com/uber/prototool#prototool-descriptor-set)

Either I am doing something wrong. Please educate me on this.

**Comment by Tochemey** [comment]
I would like to know whether there is a way not to return the last file as the FileDescriptor because prototool tend to package everything in one. I even tried generating for each proto but I still faced the same challenge.

**Comment by jhump** [comment]
@Tochemey, the API to use if you want _all_ of the files in the descriptor set file is the `CreateFileDescriptors`:

```go
var set descriptor.FileDescriptorSet
// ... unmarshal file into `set`
fds, err := desc.CreateFileDescriptors(set.GetFile())
```

The API entry-point related to file descriptor sets was intended to simplify the task of extracting a single file in the event that the file has a single file _plus its transitive closure_.

Anyhow, to make the API more obvious, I just added another entry point (#247), `CreateFileDescriptorsFromSet`, that will do what you're looking for, and removes a small amount of boiler-plate from using the function described above.

**Comment by Tochemey** [comment]
Thank you for the response
