### ISSUE TITLE
Protoparse doesn't include certain granular SourceCodeInfo.Locations

### ISSUE THREAD

**Issue by pedgeio** [jhump/protoreflect#245]
Example:

```proto
syntax = "proto3";

package a;

message Foo {}
```

I want to extract the specific `SourceCodeInfo.Location` for the name of the message, i.e. `Foo`.

- With `protoc`, you will get a `SourceCodeInfo.Location` with `path = [4, 0, 1]` and `span = [4, 8, 11]`, i.e. the name for the first message is between columns 9 and 12, i.e. `"Foo "`.
- With `goprotoc`, you only get a `SourceCodeInfo.Location` for `path = [4, 0]`, with `span = [4, 0, 14]`, i.e. all of `message Foo {}` (which is weird itself, I would expect it to go to the closing bracket, but this is what `protoc` does as well **EDIT**: this DOES go to the closing bracket for both `protoc` and `goprotoc`, so it does encompass the whole message, I was mistaken).

Having intermediate locations is actually useful if you were writing i.e. a Formatter and wanted to automatically change a name. They're also referenced in the `descriptor.proto` documentation https://github.com/protocolbuffers/protobuf/blob/0c3f43a6190b77f1f68b7425d1b7e1a8257a8d0c/src/google/protobuf/descriptor.proto#L778

Not super high priority, but adding locations for elements within `*DescriptorProto` messages (names, numbers, labels) would be helpful. We might want to match `protoc` in terms of what is actually produced though.

**Comment by jhump** [comment]
@pedgeio, I think I need to see some example output. The protoparse package definitely includes this information already, and the spans even match protoc. In fact, protoparse generally has _greater_ fidelity than protoc in that it preserves comments around these points in the source that protoc does not.

For example, here are some spots produced by protoparse that demonstrate that it does capture locations for the name of the message:
https://github.com/jhump/protoreflect/blob/master/desc/protoparse/test-source-info.txt#L76
https://github.com/jhump/protoreflect/blob/master/desc/protoparse/test-source-info.txt#L212
https://github.com/jhump/protoreflect/blob/master/desc/protoparse/test-source-info.txt#L391

**Comment by pedgeio** [comment]
For the above file:

`protoc`:

```json
{"file":[{"name":"a.proto","package":"a","messageType":[{"name":"Foo"}],"sourceCodeInfo":{"location":[{"span":[0,0,4,14]},{"path":[12],"span":[0,0,18]},{"path":[2],"span":[2,0,10]},{"path":[4,0],"span":[4,0,14]},{"path":[4,0,1],"span":[4,8,11]}]},"syntax":"proto3"}]}
```

`goprotoc`:

```
{"file":[{"name":"a.proto","package":"a","messageType":[{"name":"Foo"}],"sourceCodeInfo":{"location":[{"span":[0,0,4,14]},{"path":[12],"span":[0,0,18]},{"path":[2],"span":[2,0,10]},{"path":[4],"span":[4,0,14]},{"path":[4,0],"span":[4,0,14]}]},"syntax":"proto3"}]}
```

The difference is paths `[4,0], [4,0,1]` vs `[4], [4,0]`, the former (protoc) is correct - I'm not actually sure what path `[4]` is - might be a bug where a sub-array is taken?

**Comment by jhump** [comment]
Can you provide a source file where you see this happen? I have tests in this repo that generate correct output, so I'm curious what the difference is in the files. That definitely looks like a bug causing it to generate a truncated location :(

**Comment by pedgeio** [comment]
The above source file in the description:

```proto
syntax = "proto3";

package a;

message Foo {}
```

The two outputs in my last comment were generated on that

**Comment by jhump** [comment]
The difference between your sample, and the tests in this repo (which _do_ generate all of the expected locations) is that the message was empty. So this was tickling a bug where the logic incorrectly assumed a `nil` set of declarations for the message meant that it was a synthetic message corresponding to a map field entry. Oops.
