### ISSUE TITLE
Duplicate symbol error on Windows platform only

### ISSUE THREAD

**Issue by xitonix** [jhump/protoreflect#254]
Hi Joshua,

First of all, thank you so much for the great work you have done building the package. Fantastic job mate.

I have recently faced an issue using the `protoparse` package whenever I try to parse the descriptors of interdependent proto files on **Windows**. I tried running the same code on Mac and Linux, and both work absolutely fine. [Here](https://github.com/xitonix/protodef) is a simple repo I built to help you reproduce the issue. 

Basically I have two protocol buffer files `employee` and `person` in which `src/employee.proto` imports `src/common/person.proto`:

```
src
  employee.proto
  common
     person.proto
```

**src/Employee**

```
syntax = "proto3";
package contracts;
option go_package = "contracts";

import "common/person.proto";

message Employee {
    common.Person person = 1;
    string department = 2;
}
```

**common/Person**

```
syntax = "proto3";
package contracts.common;
option go_package = "contracts/common";

message Person {
    string name = 1;
    int32 age = 2;
    string last_name = 3;
}
```

And here is the code which parses the proto files:

```
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jhump/protoreflect/desc/protoparse"
)

func main() {
	root := flag.String("root", "./src", "Root of proto files")
	flag.Parse()

	importPaths, err := getImportPaths(*root)
	if err != nil {
		fatal(err, 1)
	}

	print(importPaths, "Import Paths")

	files, err := protoFiles(*root)
	if err != nil {
		fatal(err, 2)
	}

	print(files, "Proto Files")

	resolved, err := protoparse.ResolveFilenames(importPaths, files...)
	if err != nil {
		fatal(err, 3)
	}

	print(resolved, "Proto Files")

	parser := protoparse.Parser{
		ImportPaths: importPaths,
	}

	fileDescriptors, err := parser.ParseFiles(resolved...)
	if err != nil {
		fatal(err, 4)
	}

	fmt.Println("\nParsed Messages:")
	for _, fd := range fileDescriptors {
		fmt.Printf(" %s\n", fd.GetName())
		messages := fd.GetMessageTypes()
		for _, m := range messages {
			fmt.Printf("    %s\n", m.GetName())
		}
	}
}

func print(in []string, msg string) {
	fmt.Println(msg + ":")
	for i, p := range in {
		fmt.Printf("    %d: %s\n", i, p)
	}
}

func fatal(err error, code int) {
	fmt.Printf("E%d: %s\n", code, err)
	os.Exit(code)
}

func getImportPaths(root string) ([]string, error) {
	var dirs []string
	err := filepath.Walk(root, func(path string, f os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if f.IsDir() {
			dirs = append(dirs, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return dirs, nil
}

func protoFiles(root string) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, f os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !f.IsDir() && strings.HasSuffix(strings.ToLower(f.Name()), ".proto") {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return files, nil
}
```

The output of running the code on a Mac machine:

```
Import Paths:
    0: ./src
    1: src/common
Proto Files:
    0: src/common/person.proto
    1: src/employee.proto
Proto Files:
    0: common/person.proto
    1: employee.proto

Parsed Messages:
 common/person.proto
    Person
 employee.proto
    Employee
```

And here is the output of running the same code on a **64 bits Windows 10** box:

```
Import Paths:
    0: ./src
    1: src\common
Proto Files:
    0: src\common\person.proto
    1: src\employee.proto
Proto Files:
    0: common\person.proto
    1: employee.proto
E4: common\person.proto:5:1: duplicate symbol contracts.common.Person: already defined as message in "common/person.proto"
exit status 4
```

Both machines are using `go1.12.7` runtime. 

I was wondering if you could help me understand the difference between the parsing logic on different platforms and if there is a workaround to avoid the issue.

Many Thanks,
Alex

**Comment by jhump** [comment]
@xitonix, interesting issue. And I do see the problem. I am pretty sure it's due to the fact that import statements in the proto files use `/` as the path separator. So you've provided the correctly resolved path `common\person.proto`. But when it sees the import statement, the import path != that resolved path. So it thinks it needs to load another file. It then tries to include both `common/person.proto` _and_ `common\person.proto`, which means it has duplicates of all of the symbols for that file, and then blows up because of that.

Could you try replacing all `\` in the Windows paths with `/` and see if the problem goes away? If it does, I'll need to think about how to update `ResolveFilenames`. Maybe it needs to do the same before it returns? Or maybe the `Parser` needs a new field that helps it re-write/resolve paths (which could handle canonicalizing the path separators).

**Comment by xitonix** [comment]
Thanks for getting back to me quickly @jhump . You were absolutely right. Replacing `\` with `/` after resolving (and before Parsing) did the job:

```
resolved, _ := protoparse.ResolveFilenames(importPaths, files...)

for i := range resolved {
   resolved[i] = filepath.ToSlash(resolved[i])
}

parser := protoparse.Parser {
   ImportPaths: importPaths,
}

fileDescriptors,_ := parser.ParseFiles(resolved...)
```
I think either of the two options you have suggested will do, specially because you explicitly mentioned in the `ResolveFilenames`'s docs that 

> The resulting names should be suitable for passing to Parser.ParseFiles.

Given that the proto import paths are always with forward slash, I would personally think that you could possibly hide the requirement from the user by replacing the backslashes with forward slash regardless. I don't see any harm doing so, do you?
