### ISSUE TITLE
Is there anything we can do to keep the json-marshal ability after message merged?

### ISSUE THREAD

**Issue by jinghuazhiye** [jhump/protoreflect#265]
Great library :)
Here is my question

I'm using this library to do the following things:
- load a message descriptor dynamically from file
- unmarshal DATA to dynamic message using this message descriptor
- merge this dynamic message into a pre-generated proto message 
- marshal this pre-generated proto message to json

I'm just asking if the generated json can keep fields in the dynamically generated message but not in the pre-generated message.

You may be curious about why i should use a pre-generate proto message but not the dynamic message to serialize to json. Here is my scene

I'm using this library to create a data flow which can be dynamically updated. We have A, B, C:
- A: The receiver, which communicate to B using JSON, we call this JSON as `alpha`
- B: The proxy, communicate to C using protobuffer, we call this protobuffer as `beta`
- C: The provider, pack all data to protobuffer.
- B has many different implementations and maintained by many different people

So, if i want to update the data struct, i'm trying to only update C and A. 
In that scene, beta will be marshaled to json in B(using jsonpb), so this library will be used to keep the json fields 
Everything looks fine but if alpha contains beta, the generated message must be a specified type of beta aka pre-generated message.

Any good ideas?

**Comment by jhump** [comment]
Sorry, but I don't really understand the flow you've described or the issue.

In short, no, there is no way for a generated message to be able to emit unrecognized fields in JSON. You _must_ use a dynamic message for that.

I'm not really sure why you need to be using a generated message at all though. I think step B could be done 100% with dynamic messages.

**Comment by jinghuazhiye** [comment]
I write a short example of this

```lang=go
/* user.proto
syntax = "proto3";

message User {
   int64 id = 1;
   string nickname = 2;
}
*/

/* article.proto
syntax = "proto3";
import "user.proto";

message Article {
	User author = 1;
	int64 id = 2;
	int64 publish_time = 3;
}
*/

// 1. client call service A to get article data along with author data
func HttpGet() string {
	ar := Article{} // pre-generated pb data AKA Article

	// 2. service A call proxy library to get a specified typed user data.

	// try to use proto reflect to avoid to update service A if data structure of author is updated
	// inside:
	// i. get raw proto data from somewhere(user service for example)
	// ii. load message desc dynamically
	// iii. unmarshal raw proto data to dynamicMessage
	// iv. merge dynamicMessage to pre-generated type User pb structure(its because we must assign this type to the pre-generated Article structure)
	// v. return the pre-generated type User
	ar.Author = b.GetUserData(1) // return pre-generated pb data AKA User

	ar.PublishTime = time.Now().UnixNano() // other business
	ar.Id = 777

	// 3. service A return the json data
	s, _ := jsonpb.Marshaler{}.MarshalToString(&ar)
	return s
}

```

**Comment by jinghuazhiye** [comment]
> In short, no, there is no way for a generated message to be able to emit unrecognized fields in JSON. You _must_ use a dynamic message for that.

Thanks for the clarify, i think my workflow is a dead end and i will try other way 👍 


> 
> I'm not really sure why you need to be using a generated message at all though. I think step B could be done 100% with dynamic messages.

If we can reference a ```proto.Message``` but not ```User``` in the ```Article``` type above, then I think all the problems are solved, is that correct?

**Comment by jhump** [comment]
> If we can reference a proto.Message but not User in the Article type above for field author, then I think all the problems are solved, is that correct?

You can't do that either. `protoc-gen-go` generates `Article` to strongly refer to `User`. The solution is to _not_ use `Article`, but to use a dynamic message for that instead.

I've built a system that I think is kind of like what you're doing. It provided a REST+JSON API on top of protobuf-based RPC. It would use service reflection to periodically query for updated descriptors from the backend. It would use those to unmarshal incoming JSON and re-marshal to proto, which would then be sent to the backends. Then the reverse happens for responses (binary-encoded response from server is unmarshaled using descriptors and then re-marshaled to JSON to send back to client). Anyhow, the key was that the proxy layer _only_ dealt with descriptors and dynamic messages, instead of trying to be hybrid.

**Comment by jinghuazhiye** [comment]
> > If we can reference a proto.Message but not User in the Article type above for field author, then I think all the problems are solved, is that correct?
> 
> You can't do that either. `protoc-gen-go` generates `Article` to strongly refer to `User`. The solution is to _not_ use `Article`, but to use a dynamic message for that instead.

Just being curious, is `protoc-gen-go` do this for purpose, do you know why? 

> 
> I've built a system that I think is kind of like what you're doing. It provided a REST+JSON API on top of protobuf-based RPC. It would use service reflection to periodically query for updated descriptors from the backend. It would use those to unmarshal incoming JSON and re-marshal to proto, which would then be sent to the backends. Then the reverse happens for responses (binary-encoded response from server is unmarshaled using descriptors and then re-marshaled to JSON to send back to client). Anyhow, the key was that the proxy layer _only_ dealt with descriptors and dynamic messages, instead of trying to be hybrid.

Yes, that will be a solution just as you said above `always use dynamic message`.
But that is a little bit too heavy for our system :)
I think the main barrier to do so is i can't see the benefits of using dynamic message as a whole response. It looks better if we use this REST+JSON layer as a `gateway` for RPC services. You have opened my mind. That thing might be a good direction for our system.

**Comment by jhump** [comment]
> Just being curious, is protoc-gen-go do this for purpose, do you know why?

Is there a purpose that the struct is generated with `User` as the field type, instead of `proto.Message`? The answer is definitely "yes": it's for type safety. Strongly-typing the APIs makes it less error-prone and more clearly communicates the API's "contract". It only becomes a problem when you have an app that does not want to know the contract and wants to behave much more generically (such as a proxy).

**Comment by jinghuazhiye** [comment]
> > Just being curious, is protoc-gen-go do this for purpose, do you know why?
> 
> Is there a purpose that the struct is generated with `User` as the field type, instead of `proto.Message`? The answer is definitely "yes": it's for type safety. Strongly-typing the APIs makes it less error-prone and more clearly communicates the API's "contract". It only becomes a problem when you have an app that does not want to know the contract and wants to behave much more generically (such as a proxy).

So do you think it could be an ability of `protoc-gen-go`?

**Comment by jhump** [comment]
> So do you think it could be an ability of protoc-gen-go?

Sorry, I don't understand the question. Would could be an ability of protoc-gen-go?

**Comment by jinghuazhiye** [comment]
> > So do you think it could be an ability of protoc-gen-go?
> 
> Sorry, I don't understand the question. Would could be an ability of protoc-gen-go?

I mean maybe we could add an option to protoc-gen-go which will generate proto.Message other than specific type for `message` fields. Is it technically possible?

Sorry for my poor english.

**Comment by jhump** [comment]
> I mean maybe we could add an option to protoc-gen-go which will generate proto.Message other than specific type for message fields. Is it technically possible?

It is _technically_ possible. However, I seriously doubt the Go protobuf team would be willing to make such a change. Losing type-safety seems completely counter to protobuf philosophy. Sorry.

Anyhow, `protoc-gen-go` is not part of this repo. If you want to ask its maintainers, you'd do so in a [different repo](https://github.com/golang/protobuf/tree/master/protoc-gen-go).

Like I said before, I think the right way to do what you're trying to do is to use dynamic messages only for that part.

**Comment by jinghuazhiye** [comment]
> > I mean maybe we could add an option to protoc-gen-go which will generate proto.Message other than specific type for message fields. Is it technically possible?
> 
> It is _technically_ possible. However, I seriously doubt the Go protobuf team would be willing to make such a change. Losing type-safety seems completely counter to protobuf philosophy. Sorry.
> 
> Anyhow, `protoc-gen-go` is not part of this repo. If you want to ask its maintainers, you'd do so in a [different repo](https://github.com/golang/protobuf/tree/master/protoc-gen-go).
> 
> Like I said before, I think the right way to do what you're trying to do is to use dynamic messages only for that part.

Ok, thank you for the clarify :)
