### ISSUE TITLE
protoparse: aggregate values in uninterpreted options differ from those generated by protoc

### ISSUE THREAD

**Issue by stapelberg** [jhump/protoreflect#274]
With the following .proto file, I get different results between protoc and the protoreflect package:

```
syntax = "proto2";

service ReproService {
  option (.api.service) = {
    collection: {
      name: "repro"
    }
  };

  rpc Repro(ReproRequest) returns (ReproResponse) {
    option (repro.policy) = {
      request_policies {
        selector: "repro"
      }
    };
  }
}
```

The difference in the ServiceDescriptorProto I’m getting is (-protoc +protoreflect):
```
  []*descriptor.ServiceDescriptorProto{
- 	s`name:"ReproService" method:<name:"Repro" input_type:"ReproRequest" output_type:"ReproResponse" options:<uninterpreted_option:<name:<name_part:"repro.policy" is_extension:true > aggregate_value:"request_policies { selector : \"repro\" }" > > > options:<uninterpreted_option:<name:<name_part:".api.service" is_extension:true > aggregate_value:"collection : { name : \"repro\" }" > > `,
+ 	s`name:"ReproService" method:<name:"Repro" input_type:"ReproRequest" output_type:"ReproResponse" options:<uninterpreted_option:<name:<name_part:"repro.policy" is_extension:true > aggregate_value:"{ request_policies{ selector: \"repro\" } }" > > > options:<uninterpreted_option:<name:<name_part:".api.service" is_extension:true > aggregate_value:"{ collection{ name: \"repro\" } }" > > `,
  }
```

You can see three kinds of differences:
1. curly braces
2. whitespace placement 
3. colon presence (after “collection”)

I tried fixing this, but it’s not obvious to me what needs changing. I could make changes in the code to fix some of the 3 differences, but not all at the same time. Any ideas?

**Comment by jhump** [comment]
Could you provide the full example proto? The given example has no imports but references `.api.service` and `repro.policy` custom options.

**Comment by jhump** [comment]
BTW, if you wanted to look at fixing this, the code is here:
https://github.com/jhump/protoreflect/blob/master/desc/protoparse/parser.go#L1086

**Comment by stapelberg** [comment]
Not quite sure why the options matter, as I’m only parsing, not linking, but here is a self-contained version of the above proto:

```
syntax = "proto2";

message FieldPolicy {
  optional string selector = 1;
}

message MethodPolicy {
  repeated FieldPolicy request_policies = 2;
}

extend proto2.MethodOptions {
  optional MethodPolicy policy = 77;
}

message ServiceConfig {
  optional string name = 1;
}

extend proto2.ServiceOptions {
  optional ServiceConfig service = 66;
}

service ReproService {
  option (service) = {
    collection: {
      name: "repro"
    }
  };

  rpc Repro(ReproRequest) returns (ReproResponse) {
    option (policy) = {
      request_policies {
        selector: "repro"
      }
    };
  }
}

```

**Comment by jhump** [comment]
@stapelberg, I was looking at addressing this in the "v2" future replacement of protoparse. But I'm not sure how to reproduce. How do you get `protoc` to leave options uninterpreted?

You can see the work in progress over [here](https://github.com/jhump/protocompile/pull/6/files#r937019005).

**Comment by stapelberg** [comment]
Sorry for the slow reply — it’s been a while since I filed this, so I had to page a bunch of context back in :)

In the original testing that resulted in this bug report, I used the `proto2::compiler::Parser` class directly.

Indeed, `protoc` by default doesn’t like uninterpreted options and complains instead of spitting out a descriptor set.

You can use the following quick & dirty patch against the https://github.com/protocolbuffers/protobuf repository to make `protoc` not mind uninterpreted options:

```diff
diff --git i/src/google/protobuf/descriptor.cc w/src/google/protobuf/descriptor.cc
index cbc9660ce..68d891515 100644
--- i/src/google/protobuf/descriptor.cc
+++ w/src/google/protobuf/descriptor.cc
@@ -4082,7 +4082,7 @@ class DescriptorBuilder {
   friend class OptionInterpreter::AggregateOptionFinder;
 
   static inline bool get_allow_unknown(const DescriptorPool* pool) {
-    return pool->allow_unknown_;
+    return true;
   }
   static inline bool get_enforce_weak(const DescriptorPool* pool) {
     return pool->enforce_weak_;
```

Afterwards, I used `./protoc --descriptor_set_out=/tmp/desc.proto --proto_path=/tmp /tmp/optionsrepro.proto`, where `optionsrepro.proto` is the message from https://github.com/jhump/protoreflect/issues/274#issuecomment-528394122

Hope this helps, and thanks for taking a look
