### ISSUE TITLE
protoparse: add mechanism to detect unused imports

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#281]
`protoc` prints warnings for unused imports, which is very useful information. It would be great if we could have something along the lines of an `UnusedImportReporter` on `Parser`.

This could be done as a post-compile operation, which is fine, but this seems so universally useful that it might be good to add it to protoparse directly. Also given that this can touch on unknown types within a Protobuf definition, it might be nice to just have within protoparse.

Example:

```go
type UnusedImport struct {
  // ImportName is the name of the unused import, i.e. "google/protobuf/any.proto".
  ImportName string
  // File is the file path that contains the unused import.
  // This should correspond with GetName() on *desc.FileDescriptor.
  File string
}

type UnusedImportReporter func(UnusedImport)

type Parser struct {
  ...
  UnusedImportReporter UnusedImportReporter
}
```

**Comment by jhump** [comment]
I was thinking about something similar recently. Though I think it should be a general warning reporter, so it could also report warnings for files that have no syntax declaration (which protoc also does).

**Comment by pedgeio** [comment]
That would be good, but I would personally err on the side of not getting into linting territory too much (neither of which these are, I think). `protoc` has been adding warnings for specific lint failures recently, and I want to keep compiling as compiling, and linting as linting.

I think unused imports and syntax fall in the category of compiling though.

**Comment by bufdev** [comment]
Hey, thought: do you think this is something we could keep in mind as part of v2? That might be the best place to do it.

**Comment by jhump** [comment]
I totally plan to address it. Not sure it needs to wait until a v2, but maybe that will be the time/place to add it.
