### ISSUE TITLE
Panics on reference to a map which has <string, nil> item.

### ISSUE THREAD

**Issue by jinut2** [jhump/protoreflect#282]
refer [here](https://github.com/ktr0731/evans/issues/197) for more details

**Comment by jhump** [comment]
This is expected: it means you are using an uninitialized `dynamic.Message`, which is not a valid message (it also has no descriptor).

You have to actually instantiate the message using one of the factory methods, such as `dynamic.NewMessage`.

**Comment by jhump** [comment]
Actually, the stack trace in that other issue suggests it has nothing to do with a `<string, nil>` item in a map. The actual message itself is `nil`, so it panics when it tries to de-reference it to return the `md` descriptor field.

This is just incorrect usage of the library. Sorry.

**Comment by ktr0731** [comment]
Hi, @jhump. 
I think the issue is not caused by a misusage of the library. Actually, `grpcurl` also panics with the same response, but generated client by `protoc-gen-go` didn't panic.

Thanks.

**Comment by jhump** [comment]
> I think the issue is not caused by a misusage of the library.

@ktr0731, I need a lot more info. The original bug was just about the code panic'ing in a particular method if the receiver is nil or the message is uninitialized. But that method _should_ panic under those conditions.

If there is a bug somewhere else that causes it be nil when it should not, then I'd be happy to dig into it. But there is no real description of the problem in this bug: what is it you are doing that results in a panic? Can you provide a repro case?

**Comment by ktr0731** [comment]
@jhump 
> The original bug was just about the code panic'ing in a particular method if the receiver is nil or the message is uninitialized.

Yes, I'm understanding it. 

However, at least Evans (a gRPC client I wrote with `protoreflect`) doesn't initialize `dynamic.Message` without `dynamic.NewMessage`, so I thought the bug isn't caused by misuse.

I created a repro, see [the repo](https://github.com/ktr0731/grpc-map-empty-val-test) for more details. 
As a precondition, I launched a gRPC service that returns a message contains a map. The map has a key, its value is `nil` (the same situation with the issue title's one).

Next, I've tried to communicate the server with `grpcurl`.  The result, `grpcurl` also panicked.

After that, I've tried to communicate the server with the generated client, then it didn't panic.

I think `protoreflect` should also return the same response because the generated client returns normally.

## gRPCurl stacktrace
```
$ make run/grpcurl
grpcurl 1.4.0
grpcurl -plaintext :50051 api.Service.GetMap
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b3325]

goroutine 1 [running]:
github.com/jhump/protoreflect/dynamic.(*Message).GetMessageDescriptor(...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/dynamic_message.go:169
github.com/jhump/protoreflect/dynamic.validElementFieldValueForRv(0xc000140d00, 0x16526c0, 0x0, 0x16, 0x156c900, 0xc0001aed20, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/dynamic_message.go:1924 +0x935
github.com/jhump/protoreflect/dynamic.validElementFieldValue(0xc000140d00, 0x16526c0, 0x0, 0x156c900, 0xc0001aed20, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/dynamic_message.go:1871 +0xa8
github.com/jhump/protoreflect/dynamic.(*Message).putMapField(0xc0001c7440, 0xc000140c00, 0x156c900, 0xc0001aecf0, 0x16526c0, 0x0, 0x0, 0xc000140c00)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/dynamic_message.go:1193 +0xf4
github.com/jhump/protoreflect/dynamic.(*Message).addRepeatedField(0xc0001c7440, 0xc000140c00, 0x16526c0, 0xc0001c7620, 0xc0000fafd8, 0x118baf4)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/dynamic_message.go:1604 +0x3c2
github.com/jhump/protoreflect/dynamic.mergeField(0xc0001c7440, 0xc000140c00, 0x16526c0, 0xc0001c7620, 0xc000140c00, 0x16526c0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/merge.go:81 +0x62b
github.com/jhump/protoreflect/dynamic.(*Message).unmarshal(0xc0001c7440, 0xc0001ed118, 0x15aab00, 0x1652708, 0x16526f8)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/binary.go:177 +0x33a
github.com/jhump/protoreflect/dynamic.(*Message).UnmarshalMerge(0xc0001c7440, 0xc000171420, 0x7, 0x7, 0x1590a01, 0x1cc66f0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/binary.go:149 +0x90
github.com/jhump/protoreflect/dynamic.(*Message).Unmarshal(0xc0001c7440, 0xc000171420, 0x7, 0x7, 0xc0001c7440, 0x1)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/binary.go:138 +0x5b
google.golang.org/grpc/encoding/proto.codec.Unmarshal(0xc000171420, 0x7, 0x7, 0x16526c0, 0xc0001c7440, 0xc0000fb260, 0x123687c)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/encoding/proto/proto.go:88 +0x1fb
google.golang.org/grpc.recv(0xc00000f980, 0x4a11f78, 0x1b472e0, 0xc000144400, 0x0, 0x0, 0x16526c0, 0xc0001c7440, 0x400000, 0x0, ...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/rpc_util.go:688 +0x10f
google.golang.org/grpc.(*csAttempt).recvMsg(0xc000140d80, 0x16526c0, 0xc0001c7440, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:868 +0xed
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc000140d80, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:719 +0x46
google.golang.org/grpc.(*clientStream).withRetry(0xc0000d39e0, 0xc0001ed530, 0xc0001ed500, 0x0, 0xc000171418)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:577 +0x9c
google.golang.org/grpc.(*clientStream).RecvMsg(0xc0000d39e0, 0x16526c0, 0xc0001c7440, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:718 +0x103
google.golang.org/grpc.invoke(0x172b300, 0xc000193a80, 0xc000027bc0, 0x13, 0x16526c0, 0xc0001c73e0, 0x16526c0, 0xc0001c7440, 0xc0000c3c00, 0xc00000f880, ...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/call.go:73 +0x13b
google.golang.org/grpc.(*ClientConn).Invoke(0xc0000c3c00, 0x172b300, 0xc000193a80, 0xc000027bc0, 0x13, 0x16526c0, 0xc0001c73e0, 0x16526c0, 0xc0001c7440, 0xc00000f880, ...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/google.golang.org/grpc@v1.21.0/call.go:37 +0x1b3
github.com/jhump/protoreflect/dynamic/grpcdynamic.Stub.InvokeRpc(0x1724200, 0xc0000c3c00, 0xc0001aec40, 0x172b300, 0xc000193a80, 0xc0001da8c0, 0x1729400, 0xc0001c73e0, 0xc00000f880, 0x2, ...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/jhump/protoreflect@v1.5.0/dynamic/grpcdynamic/stub.go:61 +0x2e8
github.com/fullstorydev/grpcurl.invokeUnary(0x172b300, 0xc000193a80, 0x1724200, 0xc0000c3c00, 0xc0001aec40, 0xc0001da8c0, 0x172d0c0, 0xc00024c040, 0xc0000ae0e0, 0x1729400, ...)
	/private/tmp/grpcurl-20190930-87368-12ggfrb/grpcurl-1.4.0/src/github.com/fullstorydev/grpcurl/invoke.go:165 +0x32f
github.com/fullstorydev/grpcurl.InvokeRPC(0x172b340, 0xc000170a08, 0x172a0c0, 0xc0001f6080, 0x1724200, 0xc0000c3c00, 0x7ffeefbff01a, 0x12, 0x0, 0x0, ...)
	/private/tmp/grpcurl-20190930-87368-12ggfrb/grpcurl-1.4.0/src/github.com/fullstorydev/grpcurl/invoke.go:141 +0xa60
main.main()
	/private/tmp/grpcurl-20190930-87368-12ggfrb/grpcurl-1.4.0/src/github.com/fullstorydev/grpcurl/cmd/grpcurl/grpcurl.go:546 +0x21d2
make: *** [run/grpcurl] Error 2 
```

## Generated client output
```
$ make run/client
./bin/client
&api.GetMapResponse{
  M: map[string]*api.Message{
    "foo": (*api.Message)(nil),
  },
  XXX_NoUnkeyedLiteral: struct {}{},
  XXX_unrecognized:     []uint8{},
  XXX_sizecache:        0,
}
```

**Comment by jhump** [comment]
@ktr0731, thanks for the repro case.

I'll be honest: I am really surprised that grpc and proto actually allow this. I would have expected the server to encounter an error when trying to marshal the response message that has a `nil` value in its map.

I've found the relevant part of [the spec](https://developers.google.com/protocol-buffers/docs/proto3#maps), which states that the behavior for a map with an entry that has no value is not standardized across runtimes (which sounds kind of like "undefined" to me):

> If you provide a key but no value for a map field, the behavior when the field is serialized is language-dependent. In C++, Java, and Python the default value for the type is serialized, while in other languages nothing is serialized.

A dynamic message _cannot_ represent a `nil` message -- because a `nil` dynamic message would have no descriptor. So I think my `dynamic` package will have to treat this case like C++, Java, and Python do, and substitute a default/empty message as the value.

**Comment by jhump** [comment]
@ktr0731, do you think you could try pulling down #287, to verify that it fixes things as you need? I've added test cases to serialization (binary, json, and text formats) so am pretty comfortable that the change should do the trick. But if you could confirm, that would be great.

**Comment by ktr0731** [comment]
@jhump 
Thanks for the quick fixing. I could confirm the behavior is fixed and it worked as I expected.
