### ISSUE TITLE
--descriptor_set_out equivalent in protoparse/desc?

### ISSUE THREAD

**Issue by tinyzimmer** [jhump/protoreflect#286]
It's very possible that I just can't find it in the documentation, but is there a way to take the output from a `protoparser.Parser` and get bytes in the same format that `protoc --descriptor_set_out` produces?

For example, I found out I was able to parse a compiled descriptor set by doing this:
```
func GetDescriptors(descriptorBytes []byte) (map[string]*desc.FileDescriptor, error) {
	descriptorSet := new(descriptor.FileDescriptorSet)
	if err := descriptorSet.XXX_Unmarshal(descriptorBytes); err != nil {
		return nil, err
	}
	return desc.CreateFileDescriptorsFromSet(descriptorSet)
}
```

I don't know if that was _supposed_ to work or if I just got lucky, but I am trying to see if I can accomplish the inverse somehow without having to shell out to `protoc`, and I haven't had much luck. 

Apologies if this is a foolish question.

**Comment by jhump** [comment]
@tinyzimmer, the descriptor set file is a serialized proto whose type is `google.protobuf.FileDescriptorSet`.

In Go code, that type is `*FileDescriptorSet` in the `"github.com/golang/protobuf/protoc-gen-go/descriptor"` package.

It's probably a reasonable addition to the API in the `desc` package to have something like `ToFileDescriptorSet(... desc.FileDescriptor)`. That would allow you to take the descriptors returned from the `protoparse` package and easily create a descriptor set. Then you just serialize that (via `proto.Marshal`) to a file.

Without that helper, you just have to add the files to the slice field in `*FileDescriptorSet`. But you probably also want to include imports, which means you have to recursively traverse all transitive dependencies, adding them to the slice. When you do that, you need to add a file's imports to the slice _before_ adding the file itself: in a descriptor set, all of a file's imports come before it (so the slice is in topological order).

**Comment by tinyzimmer** [comment]
Ok it was a stupid question, and you successfully answered it 😄 

The API already has https://godoc.org/github.com/jhump/protoreflect/desc#ToFileDescriptorSet, which I was using. But I was then trying to use the `XXX_Marshal` method on the returned object. Using `proto.Marshal` worked. 

Sorry for the clutter. I guess there could be a helper method to just directly return the marshaled bytes, but I don't think that is really necessary.

**Comment by tinyzimmer** [comment]
Thanks, your answer actually pointed me in the right direction and I accomplished what I was trying to do. And the API already has the `ToFileDescriptorSet` you mentioned. I just wasn't using it correctly. 

I suppose there could be a method to just take it directly to a byte slice without having to import `proto` on the package ingester side, but it's probably not necessary.

**Comment by jhump** [comment]
> And the API already has the `ToFileDescriptorSet` you mentioned.

Oh, nice. Good job, past self! :)
