### ISSUE TITLE
Error when multiple proto files exist with different package name

### ISSUE THREAD

**Issue by cw-ashutoshsharma** [jhump/protoreflect#291]
I have implemented a gRPC service in .NET Core and Enabled gRPC server reflection on it as mentioned in https://github.com/grpc/grpc/blob/master/doc/csharp/server_reflection.md

It's working fine if all proto files of the service have **the same package defined**. But if proto files have different package name then it doesn't work.

Example:
I have two proto files.

`test.proto`

    package test;
    service testService
    {
        rpc getTest(google.protobuf.Empty) returns(TestResponse)
    }
    message TestResponse
    {
        string Name = 1;
    }

and `empty.proto`. I have included this file from `protocolbuffers/protobuf` repository with package name "google.protobuf"

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/empty.proto

I am testing server-reflection using grpcui (https://github.com/fullstorydev/grpcui), it produces the error

    Failed to compute set of methods to expose: Symbol not found: test.testService
    caused by: File not found: empty.proto

I tried to debug the code.

https://github.com/jhump/protoreflect/blob/10815c273d3f96493752e245336d4b29ce8715a8/grpcreflect/client.go#L296-L302

I found that line 296 throws an error. Because dependency name only contains file name "empty.proto" and on calling `FileByFilename` returns FileDescriptor only if depName is "google/protobuf/empty.proto" 

Is it a bug or am I missing something here?

Thanks for the awesome repo. :)

**Comment by jhump** [comment]
That example source for `test.proto` references the `google.protobuf.Empty` type, but it does not have an import statement for `"google/protobuf/empty.proto"`.

This package has all of the same requirements as the official proto spec and the `protoc` compiler tool. So you can't refer to symbols defined in some other file without importing that other file.

**Comment by cw-ashutoshsharma** [comment]
I had imported empty.proto, I forgot to mention it in the example above.

Now I tried with complete import path ` "google/protobuf/empty.proto"` and kept empty.proto file at `google/protobuf` path. It worked.

Thanks for the help.
