### ISSUE TITLE
Would a release be possible?

### ISSUE THREAD

**Issue by lukesneeringer** [jhump/protoreflect#296]
protoreflect has gotten several useful features and bugfixes, but the last version-numbered-release was in August. It would be awesome if you could cut a new one if only for the minor convenience of trimming down my `go.sum` and `go.mod` files.

Thanks muchly for this great work.

**Comment by jhump** [comment]
@lukesneeringer, I just created [1.6.0](https://github.com/jhump/protoreflect/releases/tag/v1.6.0)!

**Comment by lukesneeringer** [comment]
Thanks @jhump!
