### ISSUE TITLE
UnmarshalJSON fails to deserialise json into google.protobuf.Timestamp

### ISSUE THREAD

**Issue by xitonix** [jhump/protoreflect#299]
Hi Joshua and everyone,

This could just be a question instead of an issue, but I'd appreciate it if someone could please assist me with the problem. 

I have got a proto schema on the disk with a `google.protobuf.Timestamp` field. Here is the content of the proto file:

```
syntax = "proto3";

package contracts;

option go_package = "git.ourdomain.com/contracts";
import "google/protobuf/timestamp.proto";

message EntityDefined {
 string entity_id = 1;
 google.protobuf.Timestamp defined_date_utc = 2;
 oneof authentication_oneof {
    string api_key = 3;
    string token = 4;
  }
}
```

The schema is successfully loaded into a dynamic message and it has no Unknown Fields (so `len(msg.GetUnknownFields()) == 0`). In case you need to look at the code to see how the dynamic message is loaded from the disk [here](https://github.com/xitonix/trubka/blob/master/protobuf/loader.go) is the link to my repo.

I can successfully consume the proto bytes from Kafka and unmarshal the bytes into the dynamic message by calling `msg.Unmarshal(bytesFromKafka)`. All the fields are there as expected, including the timestamp. But if I try to achieve the same thing using JSON the following code fails with `Json: cannot unmarshal object into Go value of type string` error:

```
value := `{
   "api_key": "api_key",
   "entity_id": "abcd",
   "defined_date_utc": {
      "nanos": 1000,
      "seconds": 2000
     }
}`
	
err := msg.UnmarshalJSON([]byte(value))
if err != nil {
	return log.Fatal(err)
}
```

As soon as I remove the `defined_date_utc` from the JSON input, everything works as expected. Obviously the `defined_date_utc` field is not in the unmarshalled dynamic message anymore.

```
value := `{
   "api_key": "api_key",
   "entity_id": "abcd"
}`
	
err := msg.UnmarshalJSON([]byte(value))
if err != nil {
  // We don't hit this path anymore
   return log.Fatal(err)
}
```

I am probably doing something wrong but I've miserably failed to find out the root cause so far. I would be grateful if someone could shed some light on the issue please.

Many thanks

**Comment by jhump** [comment]
@xitonix, please review the documentation for the canonical JSON format for protocol buffers:
https://developers.google.com/protocol-buffers/docs/proto3#json

Specifically: timestamps are encoded as a string in RFC 3339 format, such as `"1972-01-01T10:00:20.021Z"`.

**Comment by xitonix** [comment]
Ah! That's why! Thank you so much for the hint @jhump .
