### ISSUE TITLE
CreateFileDescriptorFromSet expects input file first, protoc produces FileDescriptorSet with input file last

### ISSUE THREAD

**Issue by pboyer** [jhump/protoreflect#3]
protoc produces the `FileDescriptorSet` in reverse topological sort order when the `--descriptor_set_out` and `--include_imports` are set. 

This means the input file on the command line is last, preceded by its imports.

`dynamic.CreateFileDescriptorFromSet` expects the input file to be first, followed by imports. This required swapping the first and last element of the `File` field of `FileDescriptorSet`.

Close if you think the documented behavior is fine. This is just a note.

**Comment by jhump** [comment]
Good catch! It should "just work" with a protoc-generated file set. So I'll change it. I had code that actually attempts to test this, and use a descriptor that was created from a fileset. *BUT* it looks like I used a bad test: the file had no imports so the fileset had only one file in it :(

**Comment by jhump** [comment]
BTW, if you have bandwidth and desire to get into any of this code, feel free to send pull requests -- they would be welcome!

**Comment by jhump** [comment]
Fixed in #6

**Comment by pboyer** [comment]
Thanks @jhump!
