### ISSUE TITLE
Consistent API for `deprecated = true`

### ISSUE THREAD

**Issue by lukesneeringer** [jhump/protoreflect#300]
Every descriptor in protocol buffers has a consistent `deprecated` extension field. It is easy to get if you know what descriptor you have:

```go
fd.GetFieldOptions().GetDeprecated()
md.GetMessageOptions().GetDeprecated()
ed.GetEnumOptions().GetDeprecated()
// etc.
```

However, if you have a generic descriptor, it is more ornery.
I would like to propose adding `GetDeprecated()` to the `desc.Descriptor` interface, with a (one-line) implementation in each descriptor type that does the above, which would allow getting the deprecated status of an arbitrary descriptor without a switch statement or similar.

**Comment by jhump** [comment]
FYI, one-ofs do not have a deprecated field.

I suppose the accessor could still be added and just documented to always return false for one-ofs. Also `IsDeprecated` would be greatly preferred over `GetDeprecated`.

If you make a pull request, I'll merge it.

**Comment by bufdev** [comment]
A note here: this would be a breaking change per semver (adding to an interface is breaking and will break any implicit impls of Descriptor)

**Comment by jhump** [comment]
Indeed. So it would have to be a function instead:
```go
func IsDeprecated(d Descriptor) bool {
    opts := d.GetOptions()
    type deprecatable interface {
        GetDeprecated() bool
    }
    depr, ok := opts.(deprecatable)
    if return ok && depr.GetDeprecated()
}
```

**Comment by lukesneeringer** [comment]
Alright, I can write that. Thanks!

**Comment by jhump** [comment]
@lukesneeringer, since the function mentioned above is fairly simple, I'm not sure it pays its freight were it added to this package's API surface area. You could just define the same function in your own package.

So is it okay with you if we close this issue?

**Comment by jhump** [comment]
@lukesneeringer, I never heard back from you, so I'm going to close this issue. (You can re-open if you have more to add.)
