### ISSUE TITLE
Compatibility between protoprint and "google.golang.org/protobuf/reflect/protoreflect"

### ISSUE THREAD

**Issue by gonzojive** [jhump/protoreflect#301]
Is it possible to use the protoprint library with the Google-authored protoreflect library?

(I'm curious about @jhump's general thoughts on the Google protoreflect library. protoprint is not provided by the Google library's functionality and is quite cool, so I'm most interested in using this part of the library.)

**Comment by jhump** [comment]
@gonzojive, I've been thinking about creating a v2 of protoreflect that uses APIv2 for the main proto libraries.

In the meantime, you will need to use v1.4 of github.com/golang/protobuf as a compatibility mechanism -- e.g. getting the descriptors using the old APIs. If you aren't working with generated messages and have descriptors from the new API, then you'd need to write a converter that can extract all of the underlying descriptor proto messages and then create `desc.FileDescriptors` from them.
