### ISSUE TITLE
Parser does not include Well-Known Types SourceCodeInfo

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#302]
Example:

```proto
// file: foo/v1/foo.proto

syntax = "proto3";

package foo.v1;

import "google/protobuf/duration.proto";

message Bar {
  google.protobuf.Duration duration = 1;
}
```

If you were to parse this via:

```go
parser := protoparse.Parser{IncludeSourceCodeInfo: true}
fileDescriptors, err := parser.ParseFiles("foo/v1/foo.proto")
if err != nil {
  return err
}
```

You get two `FileDescriptors` with names:

- `google/protobuf/duration.proto`
- `foo/v1/foo.proto`

The `FileDescriptor` for `foo/v1/foo.proto` includes `SourceCodeInfo`, but the `FileDescriptor` for `google/protobuf/duration.proto` does not.

For consistency, you'd want the `SourceCodeInfo` for `google/protobuf/duration.proto` as well. This isn't just theoretical either - `protoc-gen-swagger` from https://github.com/grpc-ecosystem/grpc-gateway breaks without it, with the error "descriptor.File should not contain nil SourceCodeInfo".

Note that `protoc` does include the `SourceCodeInfo` if you do the same with `protoc -I . --descriptor_set_out=file.bin --include_imports --include_source_info foo/v1/foo.proto`, so this also matches `protoc`.

The issue is that https://github.com/jhump/protoreflect/blob/master/desc/protoparse/std_imports.go uses the `FileDescriptorProtos` from the proto registry used with github.com/golang/protobuf, which do not include `SourceCodeInfo`.

Recommendation (which I can help with if you want): compile pre-made `FileDescriptorProtos` in a new internal package specific to protoparse. Then, if `SourceCodeInfo` is not requested, make a copy of the `FileDescriptorProto` from `standardImports` for your return value that does not include `SourceCodeInfo`.

**Comment by jhump** [comment]
Interesting case! I like your recommendation. If you have bandwidth to look into it, please go for it.

**Comment by bufdev** [comment]
I fixed this over on Buf - do you want to close this issue?

**Comment by jhump** [comment]
@bufdev, not yet. I want to update some of the Go doc to make it clear what people should expect when using `IncludeSourceCodeInfo` and these out-of-the-box files.

**Comment by jhump** [comment]
In short, the included well-known imports do not have source code info and are not expected to have source code info. If you need source code info, provide your own descriptors for these that include source code info (or, optionally, provide source code for these files, and the descriptors with source code info will be compiled from source).
