### ISSUE TITLE
Field option values attached in non-deterministic order

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#304]
Whole issue described at https://github.com/bufbuild/buf/issues/40 - thought you might have an idea here, I'll investigate

**Comment by jhump** [comment]
That's because extensions in the Go proto runtime use a `map` to store the values. By default, the Go proto runtime does not try to serialize to bytes deterministically (though there is a way to do so).

**Comment by bufdev** [comment]
Just copying from email:

That is expected: for performance reasons, the binary format does not default to being deterministic. Any place that uses maps (such as extensions, like custom descriptor options, but also map types) will use map iteration order (which is of course non-deterministic in Go).

This is actually a rather gross issue. On the one hand, the fix for your simple repro case is to explicitly serialize the descriptors with deterministic output. You can do this using the `Buffer` type in the APIv1 `proto` package, by calling its `SetDeterministic` method before calling `Marshal`. With the APIv2 API, this is a flag on the marshaler itself.

However, that won't completely solve the issue. The `protoparse` package must first store all custom options into the descriptor. And since the custom options that are being interpreted will typically not be linked into the calling program, they must be stored in raw form -- e.g. we have to serialize them to bytes and then store the raw bytes as the extension value. And right now, there is no exposed way to manipulate whether those bytes are produced deterministically or not.

There is currently an unexported `defaultDeterminism` package var in the `dynamic` sub-package, and that is what will effectively control this. One option is to expose that -- though it feels icky and would be race (since access is not guarded by any mutex). A program would have to set it once, like during initialization. It is actually only used from tests, so that tests of the binary encoding logic can verify the output bytes.

**Comment by bufdev** [comment]
Can we explore a clean way to do this?

Also just a note, `SetDeterministic` doesn't fix the repro unfortunately, but I think it makes some sense why from the above explanation.

**Comment by bufdev** [comment]
Also just a note - going in to the repo and manually setting `var defaultDeterminism = true` doesn't fix it either, I just tried it out locally

**Comment by bufdev** [comment]
I don't think this is a serialization issue (although I could be wrong here) - I'm doing a straight `printf` of the `FileDescriptorSet` in Golang, and it shows the actual array to be in different orders:

file:<name:"foo/v1/foo_options.proto" package:"foo.v1" dependency:"google/protobuf/descriptor.proto" extension:<name:"one" number:65012 label:LABEL_OPTIONAL type:TYPE_BOOL extendee:".google.protobuf.FieldOptions" json_name:"one" > extension:<name:"two" number:65014 label:LABEL_OPTIONAL type:TYPE_BOOL extendee:".google.protobuf.FieldOptions" json_name:"two" > > file:<name:"foo/v1/foo.proto" package:"foo.v1" dependency:"foo/v1/foo_options.proto" message_type:<name:"Bar" > message_type:<name:"Baz" field:<name:"bat" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"bat" options:<65012:1 65014:1 > > > syntax:"proto3" >

vs

file:<name:"foo/v1/foo_options.proto" package:"foo.v1" dependency:"google/protobuf/descriptor.proto" extension:<name:"one" number:65012 label:LABEL_OPTIONAL type:TYPE_BOOL extendee:".google.protobuf.FieldOptions" json_name:"one" > extension:<name:"two" number:65014 label:LABEL_OPTIONAL type:TYPE_BOOL extendee:".google.protobuf.FieldOptions" json_name:"two" > > file:<name:"foo/v1/foo.proto" package:"foo.v1" dependency:"foo/v1/foo_options.proto" message_type:<name:"Bar" > message_type:<name:"Baz" field:<name:"bat" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"bat" options:<65014:1 65012:1 > > > syntax:"proto3" >

Or is this still the point?

**Comment by bufdev** [comment]
Yea, this is brutally annoying:

```diff
diff --git a/internal/buf/bufos/image_writer.go b/internal/buf/bufos/image_writer.go
index c295e61..a7f5cd0 100644
--- a/internal/buf/bufos/image_writer.go
+++ b/internal/buf/bufos/image_writer.go
@@ -3,7 +3,9 @@ package bufos
 import (
        "compress/gzip"
        "context"
+       "fmt"
        "io"
+       "os"

        "github.com/bufbuild/buf/internal/buf/bufos/internal"
        "github.com/bufbuild/buf/internal/buf/ext/extimage"
@@ -60,6 +62,13 @@ func (i *imageWriter) WriteImage(
                        return err
                }
        }
+       for _, fileDescriptorProto := range image.GetFile() {
+               for _, descriptorProto := range fileDescriptorProto.GetMessageType() {
+                       for _, fieldDescriptorProto := range descriptorProto.GetField() {
+                               fmt.Fprintf(os.Stderr, "%+v\n", fieldDescriptorProto.GetOptions().XXX_unrecognized)
+                       }
+               }
+       }
```

The output differs of course.

**Comment by jhump** [comment]
Looks like `defaultDeterminism` wasn't even being correctly adhered to -- it was relying on map iteration order in one loop, even when it was supposed to be deterministic :(

Instead of exposing `defaultDeterminism`, I just added a couple of new methods to `*dynamic.Message` to help control this: `ConvertToDeterministic` and `MergeToDeterministic`. (Ugh, this type has way too wide of an API...)

I've also updated `protoparse` to use the new `ConvertToDeterministic`, when it comes time to represent custom options using the generated `*Options` types.
