### ISSUE TITLE
Is there any way to get a nested value？

### ISSUE THREAD

**Issue by qianyuyu** [jhump/protoreflect#318]
Dynamic Message
There have some methods like "TryGetMapFieldByName" or  "TryGetRepeatedFieldByName". But these methods only get the top level field value. Is there some way to get a deep nested value?
In reflectutils package,  I can use string like "A.B.C[0].D[what]" to get a value in anywhere.
At the  same time,  "TryGetMapFieldByName" or  "TryGetRepeatedFieldByName" return the interface value. When use reflect.TypeOf(returnValue), there are some time show "*dynamic.Message", but sometimes the real type of the value. This thing makes me very confused.

**Comment by jhump** [comment]
> In reflectutils package, I can use string like "A.B.C[0].D[what]" to get a value in anywhere.

That is a cool idea for a utility method. But there is no such function for that in the `dynamic` package right now. You have to do it the hard-ish way.

It shouldn't be too bad, though. Here's an example impl:
```go
type QueryElement struct {
	FieldName string
	Index *int      // optional, when FieldName is a repeated field
	Key interface{} // optional, when FieldName is a map field
}

func QueryValue(msg *dynamic.Message, query []QueryElement) (interface{}, error) {
	first := query[0]
	rest := query[1:]

	var val interface{}
	var err error
	if first.Index != nil {
		val, err = msg.TryGetRepeatedFieldByName(first.FieldName, *first.Index)
	} else if first.Key != nil {
		val, err = msg.TryGetMapFieldByName(first.FieldName, first.Key)
	} else {
		val, err = msg.TryGetFieldByName(first.FieldName)
	}
	if err != nil {
		return nil, err
	}

	if len(rest) == 0 {
		return val, nil
	}

	dm, ok := val.(*dynamic.Message)
	if !ok {
		pm, ok := val.(proto.Message)
		if !ok {
			return nil, fmt.Errorf("cannot query field from non-message value %q", first.FieldName)
		}
		md, err := desc.LoadMessageDescriptorForMessage(pm)
		if err != nil {
			return nil, err
		}
		dm = dynamic.NewMessage(md)
		if err := dm.ConvertFrom(pm); err != nil {
			return nil, err
		}
	}

	return QueryValue(dm, rest)
}
```

> When use reflect.TypeOf(returnValue), there are some time show "*dynamic.Message", but sometimes the real type of the value.

By default, this will only be the real type of the value for scalar values (e.g. not nested messages) and for the _well-known types_. However, you can create a custom message factory that will use `*dynamic.Message` even for the well-known types, and use that when you create the message (via `dynamic.NewMessageWithMessageFactory`).
```go
msgFactory := dynamic.NewMessageFactoryWithKnownTypeRegistry(
    dynamic.NewKnownTypeRegistryWithoutWellKnownTypes(),
)
```
However, the above implementation tolerates this by just converting to a `*dynamic.Message` if it gets out some other kind of message (e.g. a protoc-generated message type).

**Comment by qianyuyu** [comment]
Appreciate your answer～
