### ISSUE TITLE
reflection error - "File not found: google/api/client.proto"

### ISSUE THREAD

**Issue by stonnu** [jhump/protoreflect#321]
Hi! I am currently using a benchmarking tool (https://ghz.sh/) that imports this package for server reflection, and I was wondering if I could get clarity on this issue I ran into. I apologize in advance if this is not the correct place to ask questions about things like these, or if my question is too vague. Feel free to let me know if that is the case, and I can close this issue.

I’m also relatively new to grpc and protobufs, so I apologize for that as well.

I have a project where I define my own proto definitions, and I import a variety of google protobuf well known types and google apis.

```
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
```
 However, when I try to call my service using the benchmarking tool, it gives me an error saying “File not found: google/api/client.proto”.

I’ve searched through many posts/questions about reflection issues, and I saw that many had to do with how the proto filenames were being registered and some had to do with google protobuf well known types. However, I looked into the resulting pb.go files and saw that they had registered client.pb.go with “google/api/client.proto”.

We are using bazel to produce our go protobufs, using the compilers
```
"@io_bazel_rules_go//proto:go_grpc",
"@com_github_grpc_ecosystem_grpc_gateway//protoc-gen-grpc-gateway:go_gen_grpc_gateway".
```
and dependencies
```
"@com_google_googleapis//google/api:annotations_go_proto",
"@com_google_googleapis//google/api:api_go_proto",
```
 
Have you run into issues using google/api imports that are not well-known types before? Or does this seem like it would be an issue related to the proto file registering? Thank you so much in advance!

**Comment by bufdev** [comment]
The tldr is that google/api types are not well-known types - they need to be imported from github.com/googleapis/googleapis. Bazel is doing this for you via that dependency, but ghz will not.

**Comment by jhump** [comment]
I assume this is using the `protoparse` package?

If so, you need to supply the sources for the dependencies, just like you supply the sources for the files you are trying to compile. *OR*, if your program imports these Go packages (the Go packages generated from those protos), then their descriptors are already linked into your program. In that case, you can instruct the parser to use them like so:
```go
// This allows imports to be resolved via loading linked-in descriptors.
parser.LookupImport = desc.LoadFileDescriptor
// Now you can call parser.Parse...
```

**Comment by stonnu** [comment]
Oh I see, thank you! This makes sense. I wasn't sure at first because it wasn't complaining about google/api/annotations.proto missing.

I'll go ahead and make sure they are imported properly.
