### ISSUE TITLE
ErrorWithPos.GetPosition() panics if Pos is nil

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#324]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1509fa6]

goroutine 79 [running]:
github.com/jhump/protoreflect/desc/protoparse.ErrorWithSourcePos.GetPosition(...)
	/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/desc/protoparse/errors.go:104
```

The issue is that `GetPosition()` deferences the `Pos` pointer, and there's no validation that this pointer is always set. Will investigate the code now.

**Comment by jhump** [comment]
Oh interesting. I wonder where we are creating such an error w/ no position. (IMO, that should be a panic... but we clearly are missing some test coverage to catch that in CI instead of in the wild.)

**Comment by bufdev** [comment]
Definitely disagree that it should be a panic heh - it's not something that we can't handle as an error in the code, panics should be the equivalent of seg faults IMO

The underlying issue is yea there's probably a place it's not being set, but that should result in an empty SourcePos probably

**Comment by bufdev** [comment]
Really optimally, `GetPosition` should return `*SourcePos`, not `SourcePos`, but this would be a breaking change at this point

**Comment by bufdev** [comment]
The underlying error was `root/a/a.proto: does not exist` where `SourcePos` was nil FYI

**Comment by jhump** [comment]
But it should _never_ return a nil. The point of it being named `ErrorWithPos` is that it always has a position. If it returned a pointer, we're just moving the point of failure, but not actually fixing anything.

Anyhow, panic or not, it's an internal invariant that has been broken.

**Comment by jhump** [comment]
> The underlying error was root/a/a.proto: does not exist where SourcePos was nil FYI

Hmm. Was that from an import statement? Or was that a named file to be parsed? If the former, it should have a position attached (and is hopefully an easy fix). If the latter, it shouldn't be an `ErrorWithPos` but just an `error`.

**Comment by bufdev** [comment]
It should not be nil for sure, but that's an issue in the code, and it is possible to have a `ErrorWithSourcePos` that is created with a nil `Pos` value. Not setting it is an error that should be corrected, but it's possible with how the struct is defined (and it's happening), and this shouldn't result in a panic for an interface function for a library user

**Comment by bufdev** [comment]
The above error was returned from a FileAccessor (I just realized the `does not exist` error is a Buf error), so it's something being propogated from FileAccessor I believe

**Comment by bufdev** [comment]
> If it returned a pointer, we're just moving the point of failure, but not actually fixing anything.


This is where I strongly disagree - what we're fixing is an interface function panicking if a struct isn't correctly formed internally in protoparse. We further should fix the issue that caused this pointer to be nil within protoparse :-) but the interface function panicking is a separate error

**Comment by bufdev** [comment]
I think I found the underlying issue:

https://github.com/jhump/protoreflect/blob/0e0129d9b5cdc086cfd7f4ab01e3f7a650101fd5/desc/protoparse/parser.go#L411
https://github.com/jhump/protoreflect/blob/0e0129d9b5cdc086cfd7f4ab01e3f7a650101fd5/desc/protoparse/parser.go#L455

`importLoc` is nil on the loop over `filenames`, so if there's an incorrect input to the Parser where we do the equivalent of `protoc path/to/non-existent/file.proto`, then we'll get an error on FileAccessor, which will result in an ErrorWithSourcePos being created without a SourcePos

**Comment by bufdev** [comment]
Fixed underlying issue in https://github.com/jhump/protoreflect/pull/326
