### ISSUE TITLE
How to serialize and deserialize MessageDescriptor

### ISSUE THREAD

**Issue by dselans** [jhump/protoreflect#330]
Hi @jhump - thanks for the excellent lib.

The gist is as follows - I have a bunch of schemas that I have parsed at a previous time and have generated appropriate `MessageDescriptor`'s for each of them. My intent is to use these message descriptors at a later time to unmarshal incoming protobuf messages to dynamic messages using the appropriate `MessageDescriptor`.

I would like to store these pre-generated MessageDescriptor's in cache for later lookup. In other words, I would like to be able to marshal/encode the MessageDescriptor's to `[]byte` and then decode them at a later time back to `MessageDescriptor`'s.

Is this doable?

I see there's a bunch of funcs and methods to do various encoding/decoding but I'm not sure if I'm pursuing the wrong direction altogether.

TIA!

**Comment by jhump** [comment]
@dselans, you would supply all of the relevant/containing file descriptors to `desc.ToFileDescriptorSet`. You can then marshal that to bytes using `proto.Marshal`. You'd then `proto.Unmarshal` bytes into a `*descriptor.FileDescriptorSet` and then convert that back to descriptors using `desc.CreateFileDescriptorsFromSet`.

**Comment by dselans** [comment]
@jhump - that totally worked. Thank you :)

What would it take to get a `*desc.MessageDescriptor` into `[]byte` and back into `*desc.MessageDescriptor`?

Right now, the flow that you suggested consists of 5+ operations. Would be nice to simplify this a bit:

1. Instantiate a `FileDescriptorSet`
2. Unmarshal the "cached" file descriptor set bytes to `*FileDescriptorSet`
3. `desc.CreateFileDescriptorFromSet`
4. `FindMessage(..)` on the file descriptor
5. `dynamic.NewMessage(newMessageDesc)`

What would be the best way to approach adding such functionality? Optimally, `*desc.MessageDescriptor` would have a `Marshal` and `Unmarshal` but I dunno if that makes sense.

Thank you for responding so quickly 😃

**Comment by jhump** [comment]
>  Optimally, *desc.MessageDescriptor would have a Marshal and Unmarshal but I dunno if that makes sense.

That does not really make sense -- that would seem to suggest you are only marshaling the message descriptor, which is not the case. The message descriptor alone is insufficient to properly rehydrate a descriptor when unmarshalling: you need the message's file descriptor and all of its transitive dependencies (hence the need to marshal a file descriptor set).

TBH, I don't believe this is a common enough use case to justify any more surface area in the protoreflect API. And five steps is not too many IMO. If you want to streamline it, I'd just create a helper function in your own code base. That also gives you flexibility on how to further tailor to your use case. If you want the serialized form to know the single message descriptor you care about (so you can unmarshal without having to supply the name along with the descriptor set), you could do that by including the name in whatever specialized serialized form you choose.

**Comment by dselans** [comment]
> you need the message's file descriptor and all of its transitive dependencies (hence the need to marshal a file descriptor set).

Got it. Thank you very much for the thorough explanation. I have currently no basis on the perf/steps involved, it is just a guess. Most importantly, your advice got me unblocked - thanks again!
