### ISSUE TITLE
LoadFileDescriptor with dependency proto fails on Windows

### ISSUE THREAD

**Issue by navono** [jhump/protoreflect#335]
# Env
OS: Win 10 1909
protoreflect Version: 1.7.0

# Description
I have a proto file,  contains some other proto dependencies like: gogole standard proto. 
Use `desc.LoadFileDescriptor(xx/yy/custom.proto)`  will failed.

in `imports.go`, it will translate proto file path:

```
func ResolveImport(importPath string) string {
	importPath = clean(importPath)
	globalImportPathMu.RLock()
	defer globalImportPathMu.RUnlock()
	reg := globalImportPathConf[importPath]
	if reg == "" {
		return importPath
	}
	return reg
}

func clean(path string) string {
	if path == "" {
		return ""
	}
	path = filepath.Clean(path)
	if path == "." {
		return ""
	}
	return strings.TrimPrefix(path, dotPrefix)
}
```

for example, from "google/protobuf/any.proto" to "google\protobuf\any.proto", cause not found in `filesCache`.

**Comment by jhump** [comment]
Ah, interesting. So it should just use the `path` package, not `path/filepath` (which is OS-sensitive).

**Comment by bufdev** [comment]
@jhump fyi we do `filepath.Clean(filepath.ToSlash(path))` on everything inside buf, and only speak in terms of slash-paths, this might be a strategy you want to do.
