### ISSUE TITLE
When I deserialize bytes into dynamic message, I can't print repeated field.

### ISSUE THREAD

**Issue by Hank00AAA** [jhump/protoreflect#348]
[relate issue](https://github.com/golang/protobuf/issues/1191)
I use this pkg to parse proto file at runtime, and I successfully deserialize []byte to a dynamic.Message, but the problem happen, My message have repeated field, but when I try ```  fmt.Println(message) ```, I only get not repeated field and lost all repeated field in output. 

How can I print all field in message?

**Comment by jhump** [comment]
There are no known issues like you describe. I think I'll need to some code samples of how you are building the descriptor (and the proto source file you are parsing) and also include example serialized bytes and the output you are seeing vs. the output you expect.
