### ISSUE TITLE
Is there a way that we can reconstruct info from non-link FileDescriptorProto?

### ISSUE THREAD

**Issue by thetruechar** [jhump/protoreflect#353]
My situation is to parse proto files to json for further use, it's common that some files depend on others, but I don't want this blocking the parsing process, so the protoparse.ParseFilesButDoNotLink seems a good start.
The problem is ParseFilesButDoNotLink will put all options in UninterpretedOption([among other side effects you mentioned in comments](https://github.com/jhump/protoreflect/blob/master/desc/protoparse/parser.go#L250)), it's reasonable, but once the dependencies are resolved(by parsing more files one day later), I want to treat the unlinked FileDescriptorProto like normal completed linked one. I tried desc.CreateFileDescriptor of the unlinked FileDescriptorProto, it seems that the UninterpretedOption remains there.
So is there a way that I can preserve all information in proto files and linked them all once the conditions are suit to generate desc.FileDescriptor? Thanks in advance.

**Comment by jhump** [comment]
I'm not sure I understand your use case. Why do you want the descriptor proto if you don't have enough info to actually link it? What is it you need to do with it? You may be better off hanging on to the proto source instead of a parsed-but-unlinked descriptor.

**Comment by thetruechar** [comment]
I want to use the json format descriptor(whether linked or not) for further process, stored in db, or which may be manipulated in other tools like json editor or something.

**Comment by jhump** [comment]
Sure. But, specifically, what is the value of storing unlinkable protos in this database? Why is it you need to use `ParseFileButDoNotLink`, instead of a normal parse+link, and how is it valuable to have unlinked/unlinkable files in the db?

**Comment by thetruechar** [comment]
Just some ideas, I always struggled to use protoc when there are multiple packages that have some dependencies among them, so I want to solve the dependency issue in a visual way.
