### ISSUE TITLE
MarshalJSONPB don't comply with protobuf json mapping rules 

### ISSUE THREAD

**Issue by joshua0x** [jhump/protoreflect#364]
regards protobuf type , int64/uint64 , should convert to string in json 

https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by jhump** [comment]
Could you provide a code example that demonstrates the bug that you think you've found? What exactly are you doing that isn't conforming to the spec?

**Comment by joshua0x** [comment]
@jhump 

`package main
//主要是测试json 对比结果---pASS
// 实测结果: json cmd=108 , wns 80

import (
	"fmt"
	example "../proto"
	"github.com/golang/protobuf/proto"

	jsonpb2 "github.com/golang/protobuf/jsonpb"

	"github.com/jhump/protoreflect/desc/protoparse"
	"github.com/jhump/protoreflect/dynamic"
)

var repeated_bytes  = [][]byte{[]byte("123"),[]byte("456")}
var optional_byes = []byte("123")
var indent = " "
//传值 nil  ,
//未传值
//增加default
func genBin(src *example.MsgBody)[]byte {
	bs,_ := proto.Marshal(src)
	return bs
}

func jstd(a []byte) string{
	obj := example.MsgBody{}
	err := proto.Unmarshal(a,&obj)
	if err != nil {
		fmt.Println("old err",err)
	}

	m := jsonpb2.Marshaler{
		EnumsAsInts:   true,
		EmitDefaults:  false,
		Indent:        indent,
		OrigName:      true,
	}
	res, err := m.MarshalToString(&obj)
	fmt.Println("jstd \n ",res)
	return res
}

func new2(a []byte) string{
	//proxy -> json
	var mobj *dynamic.Message
	{
		p := protoparse.Parser{}
		fdl,err := p.ParseFiles("./proto/example.proto")
		if err!= nil {
			fmt.Println(err)
			return ""
		}
		md := fdl[0].FindMessage("example.MsgBody")
		mobj = dynamic.NewMessage(md)
	}
	err := proto.Unmarshal(a,mobj)
	if err != nil {
		fmt.Println("new ",err)
	}
	{
		bs,err:= mobj.MarshalJSONPB(&jsonpb2.Marshaler{
			OrigName:     true,
			EnumsAsInts:  true,
			Indent:       indent,
			AnyResolver:  nil,
		})
		fmt.Println("new err ",err,string(bs))
		return string(bs)
	}

}
func cmpJhumpVsAdapter() {
	//ui := uint64(123)
	d1 := float64(1)
	d2 := float32(2)
	d3 := int32(3)
	d4 := int64(4)
	d5 := uint64(5)

	d6 := uint32(6)
	d7 := d3
	dstr := "123"
	dbool := false
	dx := example.MsgBody_home
	obj := example.MsgBody{
		Double_1:          &d1,
		Float_2:          	&d2,
		Int32_3:           &d3,
		Int64_4:           &d4,
		Uint64DestUin:     &d5,
		Uint32FlowerCount: &d6,
		Sint32ItemId:      &d7,
		Sint64ItemGroupId: &d4,
		Uint32CourseAbsId: &d6,
		StrFromUinNick:    &dstr,
		BoolA:             &dbool,
		Sb:                optional_byes,
		Type:&dx,
		Mii: map[int64]int64{1:2,2:3},
		Mii2:map[int32]int64{1:2,2:3},
		Mii3:map[int64]int32{1:2,2:3},

	}

	id := uint32(0)
	obj.Uint32CourseAbsId = &id
	bs , _ := proto.Marshal(&obj)
	b := new2(bs)
	c := jstd(bs)
	fmt.Println("equal ",b==c)
}

func main(){
	cmpJhumpVsAdapter()
}
`
--- output json
`  {
 "double_1": 1,
 "float_2": 2,
 "int32_3": 3,
 **"int64_4": "4",**
 "uint64_dest_uin": "5",
 "uint32_flower_count": 6,
 "sint32_item_id": 3,
 "sint64_item_group_id": "4",
 "uint32_course_abs_id": 0,
 "str_from_uin_nick": "123",
 "bool_a": false,
 "sb": "MTIz",
 "mii": {
  "1": "2",
  "2": "3"
 },
`

` {
 "double_1": 1,
 "float_2": 2,
 "int32_3": 3,
 _"int64_4": 4,_
 "uint64_dest_uin": 5,
 "uint32_flower_count": 6,
 "sint32_item_id": 3,

 "uint32_course_abs_id": 0,
 "str_from_uin_nick": "123",
 "bool_a": false,
 "sb": "123",
}
`

**Comment by joshua0x** [comment]
> @joshua0x, could you provide a code example that demonstrates the bug that you think you've found? What exactly are you doing that isn't conforming to the spec?

`func new2(a []byte) string{
	//proxy -> json
	var mobj *dynamic.Message
	{
		p := protoparse.Parser{}
		fdl,err := p.ParseFiles("./proto/example.proto")
		if err!= nil {
			fmt.Println(err)
			return ""
		}
		md := fdl[0].FindMessage("example.MsgBody")
		mobj = dynamic.NewMessage(md)
	}
	err := proto.Unmarshal(a,mobj)
	if err != nil {
		fmt.Println("new ",err)
	}
	{
		bs,err:= mobj.MarshalJSONPB(&jsonpb2.Marshaler{
			OrigName:     true,
			EnumsAsInts:  true,
			Indent:       indent,
			AnyResolver:  nil,
		})
		fmt.Println("new err ",err,string(bs))
		return string(bs)
	}

}`

`
func jstd(a []byte) string{
	obj := example.MsgBody{}
	err := proto.Unmarshal(a,&obj)
	if err != nil {
		fmt.Println("old err",err)
	}

	m := jsonpb2.Marshaler{
		EnumsAsInts:   true,
		EmitDefaults:  false,
		Indent:        indent,
		OrigName:      true,
	}
	res, err := m.MarshalToString(&obj)
	fmt.Println("jstd \n ",res)
	return res
}`

compare MarshalJSONPB result with   golang/protobuf/jsonpb  
diff  @ int64 types

**Comment by jhump** [comment]
Sorry but I can't get that code to compile nor do I have access to your example proto file.

As you can see from the source, this repo already intends to emit strings in [these](https://github.com/jhump/protoreflect/blob/master/dynamic/json.go#L386) [cases](https://github.com/jhump/protoreflect/blob/master/dynamic/json.go#L403), and there are [test cases](https://github.com/jhump/protoreflect/blob/master/dynamic/json_test.go#L26) which in fact attempt to exercise all scalar types and compare the output with the standard `jsonpb` package.

So in order to see and understand (and fix) whatever it is you are seeing, I need a runnable example. You can greatly simplify from that example -- just the smallest repro case you can construct.
