### ISSUE TITLE
create a dynamic client

### ISSUE THREAD

**Issue by kotyara85** [jhump/protoreflect#369]
```go
package main

import (
    "context"
    "crypto/tls"
    "time"

    "github.com/davecgh/go-spew/spew"
    "github.com/jhump/protoreflect/grpcreflect"
    "google.golang.org/grpc"
    "google.golang.org/grpc/credentials"
    reflectpb "google.golang.org/grpc/reflection/grpc_reflection_v1alpha"
)

func main() {
    creds := credentials.NewTLS(&tls.Config{InsecureSkipVerify: false})
    opts := []grpc.DialOption{
        grpc.WithTransportCredentials(creds),
    }
    ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
    defer cancel()
    conn, err := grpc.DialContext(context.TODO(), "endpoint:443", opts...)
    if err != nil {
        panic(err)
    }
    refClient := grpcreflect.NewClient(ctx, reflectpb.NewServerReflectionClient(conn))
    spew.Dump(refClient.ListServices())
    spew.Dump(refClient.ResolveService("grpc.health.v1.Health"))
}
```

**Comment by jhump** [comment]
@kotyara85, do you have a question or an issue?

**Comment by kotyara85** [comment]
@jhump a question on how to build a dynamic grpc request and get json from the endpoint.
Thank you

**Comment by jhump** [comment]
In you sample, from the `refClient`, you can get _message_ descriptors, for requests and responses, and _service/method_ descriptors, for the actual RPC API.

You'll need to use the `dynamic` and `grpcdynamic` packages to do the rest:
* You create a dynamic message for the request (`dynamic.NewMessage(msgDescriptor)`). You can then populate it somehow -- such as unmarshaling from JSON. ([Go docs](https://pkg.go.dev/github.com/jhump/protoreflect/dynamic))
* You can then create a dynamic stub using `grpcdynamic.NewStub(grpcConn)`. With this, you can invoke a method using its method descriptor. ([Go docs](https://pkg.go.dev/github.com/jhump/protoreflect/dynamic/grpcdynamic))
* The response will be a `*dynamic.Message`. You can then marshal that to JSON to render the response.

You can also see all of this in action together in github.com/fullstorydev/grpcurl.

**Comment by kotyara85** [comment]
@jhump I will take a look, thank you

**Comment by kotyara85** [comment]
Worked as a charm, thank you!
