### ISSUE TITLE
protoparse doesn't increment nested message index for synthetic map entries

### ISSUE THREAD

**Issue by apasel422** [jhump/protoreflect#372]
Leading to issues like https://github.com/googleapis/api-linter/issues/714.

I think we're missing `nestedMsgIndex++` at https://github.com/jhump/protoreflect/blob/8269465cdf82d93fb4ec1cd601d5224f9624418a/desc/protoparse/source_code_info.go#L144-L145.

**Comment by jhump** [comment]
I just made a v1.8.1 release that includes this fix.
