### ISSUE TITLE
Code Example Marshalling Protobuf serialized messages to readable JSON

### ISSUE THREAD

**Issue by weeco** [jhump/protoreflect#375]
I have a set of `.proto` files and I'd like to deserialize a protobuf serialized message (unknown type) to a human readable JSON format. I figured out there's a protoparse package which allows me to compile the descriptors, so that I don't need the protoc binary.

I'm unsure how I can deserialize a protobuf serialized message (`[]byte` ) into JSON now. My idea is to try deserialization with all descriptors and take the first one that works. If this isn't possible I'm also fine if a user needs to specify what proto type to take.

Any guidance how to do so is appreciated.

```go
	var files map[string]string
	accessor := protoparse.FileContentsFromMap(files)
	parser := protoparse.Parser{
		Accessor:              accessor,
		ValidateUnlinkedFiles: true,
		IncludeSourceCodeInfo: true,
	}
	descriptors, err := parser.ParseFiles()
	if err != nil {
		return nil, fmt.Errorf("failed to parse proto files to descriptors: %w", err)
	}
```

**Comment by jhump** [comment]
The proto wire format does not contain schema information and it also supports unrecognized fields. That means that deserializing data into a message that was actually serialized from a different message will often succeed but with likely undesirable results. So you would need the user to specify the fully-qualified message type name.

From there, you can find the message in a file descriptor using `fd.FindMessage(fullyQualifiedName)` (returns `nil` if no such message found in the file).

Once you have a message descriptor, you create a _dynamic_ message: `dynamic.NewMessage(msgDesc)`. With that you can unmarshal from the binary format and then marshal to the JSON format and then you'll have your desired output.

**Comment by weeco** [comment]
@jhump Works perfectly, thanks for your work on this lib :-). Protobuf will soon be merged into https://github.com/cloudhut/kowl and uses protoreflect under the hood 🚀
