### ISSUE TITLE
how parse from []byte string

### ISSUE THREAD

**Issue by no6850** [jhump/protoreflect#376]
How to parse content by []byte isn't from files

**Comment by jhump** [comment]
@no6850, I assume you are asking about using the `protoparse` package to parse proto sources?

If so, you can do this by providing a custom value for the `Accessor` field of the [`protoparse.Parser`](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#Parser).

There's even a helper method in the file that lets you provide a map of file names to their in-memory contents: [`FileContentsFromMap`](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#FileContentsFromMap). This requires the source be provided as a `string` (not `[]byte`). The result can then be used as the parser's file accessor.
