### ISSUE TITLE
Optional extension fields in proto3 incorrectly produce error

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#379]
https://github.com/bufbuild/buf/issues/217

```proto
// a.proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string foo = 50001;
}
```

```
$ protoc -I . --experimental_allow_proto3_optional -o /dev/null a.proto
$ buf protoc -I . -o /dev/null a.proto
a.proto:7:3:field foo: label 'optional' is not allowed on extensions in proto3
```

https://github.com/jhump/protoreflect/blob/master/desc/protoparse/validate.go#L298

Here's the check, I'm not sure if it should just be removed, or if more work needs to be done?

**Comment by jhump** [comment]
Weird. What does it even mean for that keyword to be allowed for an extension? For a normal field, a proto3 optional is actually in a _oneof_, but oneofs are not allowed in extensions (are they?) I wonder if this is a bug in `protoc`.

**Comment by jhump** [comment]
Okay, I think this is a bug in `protoc`. Here's the descriptor it generates:

```
file {
  name: "test.proto"
  dependency: "google/protobuf/descriptor.proto"
  extension {
    name: "foo"
    extendee: ".google.protobuf.MessageOptions"
    number: 50001
    label: LABEL_OPTIONAL
    type: TYPE_STRING
    json_name: "foo"
    proto3_optional: true
  }
  syntax: "proto3"
}
```

It even sets the `proto3_optional` field on the descriptor, which isn't right because proto3 optional fields are implicitly inside of a single-field oneof.

For example:
```proto
syntax = "proto3";

message Foo {
  optional string foo = 50001;
}
```
Yields this descriptor:
```
file {
  name: "test2.proto"
  message_type {
    name: "Foo"
    field {
      name: "foo"
      number: 50001
      label: LABEL_OPTIONAL
      type: TYPE_STRING
      oneof_index: 0
      json_name: "foo"
      proto3_optional: true
    }
    oneof_decl {
      name: "_foo"
    }
  }
  syntax: "proto3"
}
```

**Comment by jhump** [comment]
I've filed this: https://github.com/protocolbuffers/protobuf/issues/8234
Let's see what they say.
