### ISSUE TITLE
builder: AddNestedMessage should not detach the message itself from its parent

### ISSUE THREAD

**Issue by gontard** [jhump/protoreflect#389]
When a nested message is added to a message, the message itself is detached from its parent. 

```go
grandParent := builder.NewMessage("grandParent")
parent := builder.NewMessage("parent")
child := builder.NewMessage("child")
grandParent.AddNestedMessage(parent)
println(parent.GetParent() == nil) // => print "false"
parent.AddNestedMessage(child)
println(parent.GetParent() == nil) // => print "true"
```

To workaround that, i have to re-attach its message to its parent (e.g. `grandParent.AddNestedMessage(parent)` after the nested message has been added. 
The culprit line:
https://github.com/jhump/protoreflect/blob/8255811fc3c054aab548f7208e1471b668f4c5b3/desc/builder/message.go#L490
I can't find any good reason to have such behaviour so i guess it is a bug.

Happy to open a PR if you need help.

**Comment by jhump** [comment]
@gontard, thanks for filing this bug. Wow, what an awful typo. The line you pinpointed should have been referring to the incoming _nested_ message, not the parent. Doh!

**Comment by gontard** [comment]
Already fixed 😍 Thanks a lot
