### ISSUE TITLE
Prevent interface conversion panic

### ISSUE THREAD

**Issue by carmo-evan** [jhump/protoreflect#394]
Hi!

I am trying to generate some protobuf using https://github.com/google/gnostic-grpc, which depends on protoreflect.

The openapi spec I am using is unfortunately generating some conflicting message/enum names, at least based on the error message I am receiving:

panic: interface conversion: desc.Descriptor is *desc.MessageDescriptor, not *desc.EnumDescriptor

It would be very helpful to have a proper error message, rather than a panic, when the interface conversion fails here:

https://github.com/jhump/protoreflect/blob/05026f325d15a06428b5dbb7e27cbb92b0be249a/desc/descriptor.go#L558

**Comment by jhump** [comment]
Sorry it's been over a year with no response. A patch would be welcome for this.

**Comment by jhump** [comment]
Now I realize a patch was already submitted, and I even did a review! But that PR didn't reference this issue (only a commit message did).

PR is #395
