### ISSUE TITLE
Is it possible to parse from binary proto files ?

### ISSUE THREAD

**Issue by littleningmeng** [jhump/protoreflect#420]
I have many proto files and I do `protoc -o all.pb xxx.proto ...` for packing to a single file.  
the code below will be wrong  
fds, _ := protoparse.Parser{}.ParseFiles("all.pb")  

Here is the stack  
![image](https://user-images.githubusercontent.com/26163787/132186423-d5e4974e-f369-4286-8b9f-f4a444298428.png)

**Comment by jhump** [comment]
@littleningmeng, the `protoparse` package is for parsing proto _source code_. For loading a descriptor set, created by `protoc`, you instead want to use [`desc.CreateFileDescriptorsFromSet`](https://pkg.go.dev/github.com/jhump/protoreflect/desc#CreateFileDescriptorsFromSet).

You'll have to first read the `"all.pb"` file into a `[]byte` (like using `ioutil.ReadAll`) and then you can use `proto.Unmarshal` to de-serialize that into a `*descriptorpb.FileDescriptorSet`. You can then pass that descriptor set to the above linked function and get back proper descriptors.

**Comment by littleningmeng** [comment]
@jhump Thanks a lot
I wrote the code as you guide and it worked!
