### ISSUE TITLE
ability to specify sorting of elements in a file.

### ISSUE THREAD

**Issue by jkim-coursera** [jhump/protoreflect#421]
I understand that the current protoprint behaviour sorts in this order. 
thanks again for the comprehensive documentation. 

```
	//  1. Syntax
	//  2. Package
	//  3. Imports (sorted lexically)
	//  4. Options (sorted by name, standard options before custom options)
	//  5. Messages (sorted by name)
	//  6. Enums (sorted by name)
	//  7. Services (sorted by name)
	//  8. Extensions (grouped by extendee, sorted by extendee+tag)
```

We'd like to print proto files with **Services** being defined before **Messages/Enums**. 
is there a way to specify custom sort order of elements? 
for instace 1. Syntax 2. Package 3.Imports 4. Options 5. Services 6. Messages 7 Enums

**Comment by jkim-coursera** [comment]
@jhump any possibility here by any chance?

**Comment by jhump** [comment]
@jkim-coursera, no functionality like that currently exists. I'm trying to think what such an API might look like. I think it could take a couple of possible shapes:

1. Caller provide lists of element kinds as sorting policies. So a "file sorting policy" is a list of the kinds of elements that can appear in a file. And there could also be message, enum, oneof, and service sorting policies, for controlling the order of elements in each of those kinds of blocks. If a policy is missing a kind, those elements would appear after all kinds that are present, in the same relative order as the default policy described in the package doc.
2. Caller provides a "less" function, that accepts two elements and return true if the first element should sort before the second (similar to how the `"sort"` package works). The actual type passed to the less function would be an interface that has methods for fetching things like the element kind, name, and optional number (for fields and enum values). This provides the most amount of flexibility.

I'm leaning towards the second.

**Comment by jkim-coursera** [comment]
thanks for the detailed response. 

I also agree that the second option will be much more flexible and easy to extend as things evolve. 
did you have any plans on getting this implemented anytime soon, we'll also look for an alternate solution meanwhile.
