### ISSUE TITLE
protoparse: ParseFiles ignores zero bytes that protoc errors on

### ISSUE THREAD

**Issue by WillAbides** [jhump/protoreflect#442]
A `0x00` byte outside a message causes protoc to fail with `Invalid control characters encountered in text.`, but ParseFiles ignores the byte.

```protobuf
-- a.proto --

syntax = "proto3";

message A{}
```

 is "0x00" above

**Comment by jhump** [comment]
Oof, good find! I think that the lexer incorrectly interprets the null byte as EOF.
