### ISSUE TITLE
Wasm compilation question

### ISSUE THREAD

**Issue by gedw99** [jhump/protoreflect#462]
I assume this relies on the Descriptor Set and possibly other meta data to do runtime reflection ? 

If it does then it should theoretically be possible to compile this with tinygo and run as a wasm browser client .

**Comment by jhump** [comment]
It depends on what you are trying to do. Yes, if you want to do runtime reflection for protobuf types that have been compiled to Go code, it does indeed rely on metadata. I am pretty sure this should indeed all work with wasm. There are some little things done using "unsafe", however there are alternate implementations that do not, explicitly so this library can work with any kind of runtime (the "unsafe" implementation is for performance, so the safe versions are correct).

**Comment by gedw99** [comment]
thanks @jhump for the tips :)
