### ISSUE TITLE
How to convert `MessageDescriptor` to map[string]interface{}

### ISSUE THREAD

**Issue by ngxlua** [jhump/protoreflect#464]
I want to convert MethodDescriptor to `map[string]interface{}` . I can successfully convert the MethodDescriptor obtained by `methodDescriptor.GetInputType()`, but not the one obtained by `methodDescriptor.GetOutputType()`.

```
// get MethodDescriptor
md := sd.FindMethodByName(methodName)
if md == nil {
    return nil, errors.WithStack(MethodNotFoundError)
}
```

I want to get the response structure of proto completely in the way of json, but I don't know what to do. I hope to get help. Thank you.

**Comment by ngxlua** [comment]
I also try to get the json structure through `NewDynamicMessage`

```
dMessage := dynamic.NewMessageFactoryWithDefaults().NewDynamicMessage(md)

json, err := dMessage.MarshalJSONPB(a.jsonMarshaler)
if err != nil {
    return nil, errors.WithStack(err)
}
```

However, this is not the result I want. `string(json)` should not be `null`.

```
{"detail":null}
```

**Comment by jhump** [comment]
To convert any descriptor in the `desc` package to JSON, use the `AsProto()` function and then use the `github.com/golang/protobuf/jsonpb` package to generate JSON from that protobuf message. You could also use the newer `google.golang.org/protobuf/encoding/protojson` package, but that is the new API which expects a different message interface -- you can use the `MessageV2` adapter function in `github.com/golang/protobuf/proto` to convert to the correct interface.

However, this approach will just emit the fully-qualified _name_ of the input and output types, as strings. If you want the JSON structure to instead inline the JSON representation of those message descriptors, you'd have to do something different. You could use the technique above to generate JSON for the input and output message descriptors and then store those into a map or custom struct, so the resulting JSON output is what you're looking for.

**Comment by ngxlua** [comment]
Thank you!
