### ISSUE TITLE
Multiple services in different files

### ISSUE THREAD

**Issue by manuelnp** [jhump/protoreflect#466]
I have two services defined in two different files. Everything works fine with grpcli and grpcurl but with grpcui I always get an error regarding not finding the second service symbols.

I chased down the error until protoreflect: when you define two grpc services in two files, in the method [getAndCacheFileDescriptors](https://github.com/jhump/protoreflect/blob/d551e22cd340edf9f6e515a6d3670a1f9cf7e990/grpcreflect/client.go#L238), the client stream buffer needs to be cleared before performing a second call to [send](https://github.com/jhump/protoreflect/blob/d551e22cd340edf9f6e515a6d3670a1f9cf7e990/grpcreflect/client.go#L418), otherwise the result for the second call gets appended to the stream buffer and, as the first element in the buffer got [cached](https://github.com/jhump/protoreflect/blob/d551e22cd340edf9f6e515a6d3670a1f9cf7e990/grpcreflect/client.go#L277) during the lookup for the first service, that file descriptor gets [returned](https://github.com/jhump/protoreflect/blob/d551e22cd340edf9f6e515a6d3670a1f9cf7e990/grpcreflect/client.go#L273) for the second service, causing the problem.

Despite  my utter inexperience in Go, I have make a small change 2012169a0b35b529b2565d3c5c9fb405102ebf32 which I am more than happy to merge if you see fit.

**Comment by jhump** [comment]
I don't quite follow. Are you saying you have two different services, but they are defined in files with the same name? Can you be more specific with a reproducing case?

**Comment by manuelnp** [comment]
I have two grpc service definitions: ServiceA and ServiceB, each with one rpc method, MethodA and MethodB, respectively.

If I define both services in the same file.proto, everything works fine. If I define them in two different proto files, with different names, and expose them both through the same grpc server, grpcui (due protoreflect) fails to resolve the symbols related to the second service registered. grpcli and grpcurl do not suffer this issue.

**Comment by jhump** [comment]
@manuelnp, can you provide the exact error messages you are seeing? It is strange that grpcurl would work since grpcui uses grpcurl under its hood (it imports `github.com/fullstorydev/grpcurl` to actually do most of the dynamic RPC stuff).

**Comment by manuelnp** [comment]
Sorry for the late response @jhump, I will try my best to detail the case:

**Working case:**

Define two grpc services in the same proto file [all_services.txt](https://github.com/jhump/protoreflect/files/8002586/all_services.txt)

Create a simple implementation:

```
#include <grpcpp/server.h>
#include <grpcpp/server_builder.h>
#include <sandbox/all_services.pb.h>
#include <sandbox/all_services.grpc.pb.h>

class Service_1 : public ::sandbox::Service_1::Service
{
 public:

  virtual ::grpc::Status Execute(::grpc::ServerContext*, const ::sandbox::Request*, ::sandbox::Response* response) override
  {
    *response->mutable_str() = "Service 1 working";
    return ::grpc::Status::OK;
  }
};

class Service_2 : public ::sandbox::Service_2::Service
{
 public:

  virtual ::grpc::Status Execute(::grpc::ServerContext*, const ::sandbox::Request*, ::sandbox::Response* response) override
  {
    *response->mutable_str() = "Service 2 working";
    return ::grpc::Status::OK;
  }
};

int main()
{
  ::grpc::ServerBuilder builder;
  builder.AddListeningPort("localhost:4242", ::grpc::InsecureServerCredentials(), nullptr);

  auto service1 = std::make_unique<Service_1>();
  builder.RegisterService(service1.get());
  auto service2 = std::make_unique<Service_2>();
  builder.RegisterService(service2.get());

  auto server = builder.BuildAndStart();
  server->Wait();

  return 0;
}
``` 

Output from grpcli:

![image](https://user-images.githubusercontent.com/6459618/152521925-d76b8838-7558-4367-8b21-2d50dc3ccbe4.png)

Output from grpcurl:

![image](https://user-images.githubusercontent.com/6459618/152522075-b2f1d999-5f41-4952-85a2-287fdb7aef52.png)

Output from grpcui:

![image](https://user-images.githubusercontent.com/6459618/152522208-1bcccc44-f922-4d41-8d3c-a336e94e67a7.png)

---
**NOT working case:**

Define two grpc services in two different proto files, [service_A.txt](https://github.com/jhump/protoreflect/files/8002660/service_A.txt) and [service_B.txt](https://github.com/jhump/protoreflect/files/8002680/service_B.txt)

Create a simple implementation:

```
#include <grpcpp/server.h>
#include <grpcpp/server_builder.h>
#include <sandbox/service_A.pb.h>
#include <sandbox/service_A.grpc.pb.h>
#include <sandbox/service_B.pb.h>
#include <sandbox/service_B.grpc.pb.h>


class Service_A : public ::sandbox::Service_A::Service
{
 public:

  virtual ::grpc::Status Execute(::grpc::ServerContext*, const ::sandbox::RequestA*, ::sandbox::ResponseA* response) override
  {
    *response->mutable_str() = "Service A working";
    return ::grpc::Status::OK;
  }
};

class Service_B : public ::sandbox::Service_B::Service
{
 public:

  virtual ::grpc::Status Execute(::grpc::ServerContext*, const ::sandbox::RequestB*, ::sandbox::ResponseB* response) override
  {
    *response->mutable_str() = "Service B working";
    return ::grpc::Status::OK;
  }
};

int main()
{
  ::grpc::ServerBuilder builder;
  builder.AddListeningPort("localhost:4242", ::grpc::InsecureServerCredentials(), nullptr);

  auto service1 = std::make_unique<Service_A>();
  builder.RegisterService(service1.get());
  auto service2 = std::make_unique<Service_B>();
  builder.RegisterService(service2.get());

  auto server = builder.BuildAndStart();
  server->Wait();

  return 0;
}
```

Output from grpcli:

![image](https://user-images.githubusercontent.com/6459618/152522937-c8b17606-26bf-49c2-95a9-08dec779183d.png)

Output from grpcurl:

![image](https://user-images.githubusercontent.com/6459618/152523003-3e6c1911-7de6-478b-9a85-5a8ce979f7cf.png)

Output from grpcui:

![image](https://user-images.githubusercontent.com/6459618/152527204-f088ca29-0bff-49e1-b8d1-09471afb2f76.png)

---

As you can see, although grpcli and grpcurl show the running services properly, grpcui fails at finding the Service_B symbols, the service registered last.

Moreover, if I swap the registering order in the code:

```
[...]
int main()
{
  ::grpc::ServerBuilder builder;
  builder.AddListeningPort("localhost:4242", ::grpc::InsecureServerCredentials(), nullptr);

  auto service2 = std::make_unique<Service_B>(); // Now registered first
  builder.RegisterService(service2.get());
  auto service1 = std::make_unique<Service_A>();
  builder.RegisterService(service1.get());

  auto server = builder.BuildAndStart();
  server->Wait();

  return 0;
}
```

The output from grpcui changes:

![image](https://user-images.githubusercontent.com/6459618/152523695-07ac83c8-0df7-4663-8589-c984938f8bfd.png)

grpcui claims now that Service_A is missing symbols. This led me to think that there should be and issue in the code which is requesting the proto descriptor from the exposed services.

If you analyze this [function](https://github.com/jhump/protoreflect/blob/2012169a0b35b529b2565d3c5c9fb405102ebf32/grpcreflect/client.go#L238) of protoreflec, you can see that the following line:

`resp, err := cr.send(req)`

is caching the response in a buffer inside cr (cr.stream) and, some lines afterward:

`fdResp := resp.GetFileDescriptorResponse()`

extracts only the first proto definition inside cr.stream.

If the two services are defined in the same proto file we are good to go but, if we are using to different files for defining our services, calling `resp.GetFileDescriptorResponse()` for the second service returns the proto definition for the first service, which leads to the bug I'm facing.

Aside from this, grcpcurl works in every case becase `GetFileDescriptorResponse` is exercised to retrieve the service definition. To actually call any of service with grpcurl, you do separated executions, so the buffer of cr.stream is clean every time:

![image](https://user-images.githubusercontent.com/6459618/152526413-7f7e7cbc-5ff3-4258-a0af-a96775e4a46a.png)

**Comment by jhump** [comment]
@manuelnp, ah, you never said above you were using service reflection. The description made it sound like you were passing the files to grpcurl.

This sounds like a problem in the reflection service implementation you are using. I assume if you provide the protos (via `-proto` arguments to grpcurl), everything works, right?

In order to troubleshoot the reflection service, you'd need to capture the requests/responses for that service between grpcurl and your server, so we can examine the server's responses and figure out the issue.

**Comment by manuelnp** [comment]
@jhump, grpcurl works fine in every case, no need for `-proto` argument.

The problem is exclusive of grpcui, due the implementation of `Client` class in protoreflect. 

Requests/responses between the client and the server are OK, the issue here is how the `Client` in protoreflect is handling those responses.

Lets look at the client method [getAndCacheFileDescriptors](https://github.com/jhump/protoreflect/blob/master/grpcreflect/client.go#L238) and change the code to log a little:

```
func (cr *Client) getAndCacheFileDescriptors(req *rpb.ServerReflectionRequest, expectedName, alias string) (*desc.FileDescriptor, error) {
	fmt.Print("Request ", req, "\n")
	resp, err := cr.send(req)
	fmt.Print("Response ", resp, "\n")

	if err != nil {
		return nil, err
	}
[...]
```

This is the output I get:

```
Request file_containing_symbol:"sandbox.Service_A"
Response original_request:{file_containing_symbol:"sandbox.Service_A"}  file_descriptor_response:{file_descriptor_proto:"\n\x17sandbox/service_A.proto\x12\x07sandbox\"\x16\n\x08RequestA\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\tResponseA\x12\x0b\n\x03str\x18\x01 \x01(\t2=\n\tService_A\x120\n\x07Execute\x12\x11.sandbox.RequestA\x1a\x12.sandbox.ResponseAb\x06proto3"}
Request file_containing_symbol:"sandbox.Service_B"
Response original_request:{file_containing_symbol:"sandbox.Service_B"}  file_descriptor_response:{file_descriptor_proto:"\n\x17sandbox/service_A.proto\x12\x07sandbox\"\x16\n\x08RequestA\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\tResponseA\x12\x0b\n\x03str\x18\x01 \x01(\t2=\n\tService_A\x120\n\x07Execute\x12\x11.sandbox.RequestA\x1a\x12.sandbox.ResponseAb\x06proto3"  file_descriptor_proto:"\n\x17sandbox/Service_B.proto\x12\x07sandbox\"\x16\n\x08RequestB\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\tResponseB\x12\x0b\n\x03str\x18\x01 \x01(\t2=\n\tService_B\x120\n\x07Execute\x12\x11.sandbox.RequestB\x1a\x12.sandbox.ResponseBb\x06proto3"}
Failed to compute set of methods to expose: Symbol not found: sandbox.Service_B
```

As you can see, reponse for Service_B contains both file descriptors for A and B.

Now lets clear the interal buffer stream of `Client` [here](https://github.com/jhump/protoreflect/blob/master/grpcreflect/client.go#L480) doing this:

```
func (cr *Client) initStreamLocked() error {
	if cr.stream != nil {
		return cr.resetLocked()
	}
[...]

```

The output I get is:

```
Request file_containing_symbol:"sandbox.Service_A"
Response original_request:{file_containing_symbol:"sandbox.Service_A"}  file_descriptor_response:{file_descriptor_proto:"\n\x17sandbox/service_A.proto\x12\x07sandbox\"\x16\n\x08RequestA\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\tResponseA\x12\x0b\n\x03str\x18\x01 \x01(\t2=\n\tService_A\x120\n\x07Execute\x12\x11.sandbox.RequestA\x1a\x12.sandbox.ResponseAb\x06proto3"}
Request file_containing_symbol:"sandbox.Service_B"
Response original_request:{file_containing_symbol:"sandbox.Service_B"}  file_descriptor_response:{file_descriptor_proto:"\n\x17sandbox/Service_B.proto\x12\x07sandbox\"\x16\n\x08RequestB\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\tResponseB\x12\x0b\n\x03str\x18\x01 \x01(\t2=\n\tService_B\x120\n\x07Execute\x12\x11.sandbox.RequestB\x1a\x12.sandbox.ResponseBb\x06proto3"}

```

Every response contains only the file descriptor relative the sevice I'm requesting.

The way [getAndCacheFileDescriptors](https://github.com/jhump/protoreflect/blob/master/grpcreflect/client.go#L238) is implemetend, it caches every call using the first descriptor in the response.

After the call for Service_B, `Client` internal buffer contains the descriptor of the Service_A, which was already on the internal stream because of the previous call and the descriptor of the Service_B. However, `getAndCacheFileDescriptors` extracts the first descriptor (describing Service_A) and makes a cache hits, returning it as the descriptor for the Service_B, which is wrong:

```
	// Response can contain the result file descriptor, but also its transitive
	// deps. Furthermore, protocol states that subsequent requests do not need
	// to send transitive deps that have been sent in prior responses. So we
	// need to cache all file descriptors and then return the first one (which   <- Here you state you return the first one
	// should be the answer). If we're looking for a file by name, we can be
	// smarter and make sure to grab one by name instead of just grabbing the
	// first one.
	var firstFd *dpb.FileDescriptorProto
	for _, fdBytes := range fdResp.FileDescriptorProto {
		fd := &dpb.FileDescriptorProto{}
		if err = proto.Unmarshal(fdBytes, fd); err != nil {
			return nil, err
		}

		if expectedName != "" && alias != "" && expectedName != alias && fd.GetName() == expectedName {
			// we found a file was aliased, so we need to update the proto to reflect that
			fd.Name = proto.String(alias)
		}

		cr.cacheMu.Lock()
		// see if this file was created and cached concurrently
		if firstFd == nil {
			if d, ok := cr.filesByName[fd.GetName()]; ok {    <- Here the cache hit
				cr.cacheMu.Unlock()
				return d, nil
			}
		}
[...]
```

I think I have the problem narrowed down, but I fail at explaining it, please, help me to explain it to you 😓

**Comment by jhump** [comment]
> @jhump, grpcurl works fine in every case, no need for -proto argument.

Sorry, I meant `grpcui`.

> As you can see, reponse for Service_B contains both file descriptors for A and B.

Yep, that's what I meant when I said this was something peculiar in the server reflection implementation. This is very strange behavior. But, now that I peruse [the spec](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto) it does not specify anything about the order of files or whether or not superfluous files are expected or disallowed. So I guess this is technically in spec.

I had assumed "first" because the only implementation I reviewed at the time that actually returned multiple files worked that way. (Many implementations return only exactly the requested file, so I didn't have many server implementations to test with.) I thought I had tried this with the C++ impl, so they may have changed it recently to work more like `google.protobuf.FileDescriptorSet`, where the file of interest is _last_ instead of first.

> I think I have the problem narrowed down...

I appreciate all of the details! The fix is pretty simple, but I'm afraid the one-liner patch you initially proposed is not the way to solve this. Really, instead of assuming the first file in the response is the right one, we need to actually examine all of the returned file names.

I think I can push a patch pretty soon that hopefully you can try out.

**Comment by jhump** [comment]
Ugh, actually, this seems bad that the order is not specified. While it's easy to find "the right file" for the `file_by_filename` operation, that is not true for the `file_containing_symbol` or `file_containing_extension` operations. That definitely complicates the solution and makes it much harder for the client to know _which_ file it cares about in the event that the server responds with multiple files.

I can still do something here that is robust, but it will be more complicated as each operation has to use a different strategy for picking "the right file".

**Comment by manuelnp** [comment]
In my tests, the server is working as intended, returning only the meaningful file descriptors (service and params related). It is the Client (DescriptorSourceFromServer) of protoreflect the one which is concatenating the responses of consecutive calls to the server. 

On another topic lays of course that you should not relay on first descriptor being the actual service instead of one of its parameters. But I think these are separate issues.

In any case, I will be happy to test any of your fixes, thank you for taking your time on this.

**Comment by jhump** [comment]
> returning only the meaningful file descriptors

The example you gave above for service_B was a single file with no imports. Yet the server also returned the file with service_A. How is that a meaningful file descriptor? Perhaps your actual failing case has file B _importing_ file A?

**Comment by manuelnp** [comment]
No no, the server returned only the descriptor for service B but the Client member parameter cr.stream was already filled with service_A descriptor from a previous call.

**Comment by jhump** [comment]
> No no, the server returned only the descriptor for service B but the Client member parameter cr.stream was already filled with service_A descriptor from a previous call.

That is not how that code works. It does not cache _RPC responses_ anywhere. Nor does it anywhere _manufacture_ instances of `ServerReflectionResponse`. Those response messages are deserialized from the server.

So I bet there is something fishy happening in your server: when you ask for the two files _on the same stream_, back to back, the second response includes a redundant copy of the first requested file. Your one liner is simply resetting the stream in between each call, which can make it less efficient. That is not how the reflection service is intended to be used: it's a streaming API so you can issue all requests on the same stream, which eliminates a lot of the chatty overhead and allows the server to know which files it has already sent the client on that stream, and optionally [elide them later](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L82).

Try logging all messages [sent](https://github.com/jhump/protoreflect/blob/master/grpcreflect/client.go#L457) and [received](https://github.com/jhump/protoreflect/blob/master/grpcreflect/client.go#L469) on the stream, and I think you'll see what I mean. Those are the actual messages sent to and received from the server.

**Comment by jhump** [comment]
You could also test this with `grpcurl`:
```
grpcurl -plaintext -d @ localhost:4242 grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo <<EOM
{"file_containing_symbol":"sandbox.Service_A"}
{"file_containing_symbol":"sandbox.Service_B"}
EOM
```

**Comment by manuelnp** [comment]
You are completly right, here is the response:

```
./grpcurl -plaintext -d @ localhost:4242 grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo <<EOM
{"file_containing_symbol":"sandbox.Service_A"}
{"file_containing_symbol":"sandbox.Service_B"}
EOM
{
  "original_request": {
    "file_containing_symbol": "sandbox.Service_A"
  },
  "file_descriptor_response": {
    "file_descriptor_proto": [
      "ChdzYW5kYm94L3NlcnZpY2VfQS5wcm90bxIHc2FuZGJveCIWCghSZXF1ZXN0QRIKCgJpZBgBIAEoBSIYCglSZXNwb25zZUESCwoDc3RyGAEgASgJMj0KCVNlcnZpY2VfQRIwCgdFeGVjdXRlEhEuc2FuZGJveC5SZXF1ZXN0QRoSLnNhbmRib3guUmVzcG9uc2VBYgZwcm90bzM="
    ]
  }
}
{
  "original_request": {
    "file_containing_symbol": "sandbox.Service_B"
  },
  "file_descriptor_response": {
    "file_descriptor_proto": [
      "ChdzYW5kYm94L3NlcnZpY2VfQS5wcm90bxIHc2FuZGJveCIWCghSZXF1ZXN0QRIKCgJpZBgBIAEoBSIYCglSZXNwb25zZUESCwoDc3RyGAEgASgJMj0KCVNlcnZpY2VfQRIwCgdFeGVjdXRlEhEuc2FuZGJveC5SZXF1ZXN0QRoSLnNhbmRib3guUmVzcG9uc2VBYgZwcm90bzM=",
      "ChdzYW5kYm94L1NlcnZpY2VfQi5wcm90bxIHc2FuZGJveCIWCghSZXF1ZXN0QhIKCgJpZBgBIAEoBSIYCglSZXNwb25zZUISCwoDc3RyGAEgASgJMj0KCVNlcnZpY2VfQhIwCgdFeGVjdXRlEhEuc2FuZGJveC5SZXF1ZXN0QhoSLnNhbmRib3guUmVzcG9uc2VCYgZwcm90bzM="
    ]
  }
}

```

Definitely server fault. I will look into it, thank you again for taking the time to help me.

**Comment by jhump** [comment]
@manuelnp, I'm glad you were able to confirm my suspicion about the server.

And, on that note, PR #487 should fix it. If you could pull down that branch and try it out, I'd love if you could let me know whether that does the trick for you.

**Comment by manuelnp** [comment]
@jhump, PR #487 yields the same error I'm afraid.

**Comment by jhump** [comment]
@manuelnp, I just did some debugging and found the problem. Oops 🤦 

If you have a moment, please try again with latest head of that branch.

**Comment by manuelnp** [comment]
@jhump Its working now, thanks!
