### ISSUE TITLE
Getting a descriptorpb.FileDescriptorProto from a file

### ISSUE THREAD

**Issue by edwardIshaq** [jhump/protoreflect#470]
Hi,
I"m wondering if its possible to use this library import the content of a `.proto` file and get `descriptorpb.FileDescriptorProto`
both these approaches resulted in file not found error `internal.ErrNoSuchFile` but I doubt this is the intended use case for LoadFileDescriptor. it seems like it would only load from the global loaded files. Can you please advise if there is a known way to do this using this library ? The alternative to this is to run these files in the `protoc` compiler to get the FileDescriptorProro.

```go
fd, err := desc.LoadFileDescriptor(filepath)
if err != nil {
  fmt.Printf("\nFailed: %s", err)
} else {
  fmt.Println(fd)
}

importer := new(desc.ImportResolver)
fd, err = importer.LoadFileDescriptor(filepath)
if err != nil {
  fmt.Printf("\nFailed: %s", err)
  return
} else {
  fmt.Println(fd)
}

```

Thank you 🙏

**Comment by jhump** [comment]
`desc.LoadFileDescriptor` is to load files that are linked into the binary. This is when you use `protoc` to _generate_ the Go code for the protos. This allows you to load the reflection information for Go packages that represent compiled protos.

To parse from source, you'd have to use the `desc/protoparse` package in this repo.
