### ISSUE TITLE
Get whole repeated field

### ISSUE THREAD

**Issue by krtkvrm** [jhump/protoreflect#473]
I am seeing that we have functions such as `TryGetRepeatedFieldByNumber` which would return just the value at that index of a repeated field. Internally, I see that we use m.values
[dynamic/dynamic_message.go#L1492](https://github.com/jhump/protoreflect/blob/master/dynamic/dynamic_message.go#L1492)
```go
        sl := m.values[fd.GetNumber()]
	if sl == nil {
		var err error
		if sl, err = m.parseUnknownField(fd); err != nil {
			return nil, err
		} else if sl == nil {
			return nil, IndexOutOfRangeError
		}
	}
	res := sl.([]interface{})
	if index >= len(res) {
		return nil, IndexOutOfRangeError
	}
	return res[index], nil
```

and we are returning `res[index]`.
I am not able to find any function that returns `res` as whole. 
If this is missing, can I raise a PR to just extract this out and make this a func
```
func (m *Message) GetRepeatedFieldElementsByNumber(fd *desc.FieldDescriptor, tagIndex int) ([]interface{}, error){
.
.
.
}

func (m *Message) GetRepeatedFieldElements(fd *desc.FieldDescriptor) ([]interface{}, error){
.
.
.
}

func (m *Message) getRepeatedFieldElements(fd *desc.FieldDescriptor) ([]interface{}, error))
        if fd.IsMap() || !fd.IsRepeated() {
		return nil, FieldIsNotRepeatedError
	}
	sl := m.values[fd.GetNumber()]
	if sl == nil {
		var err error
		if sl, err = m.parseUnknownField(fd); err != nil {
			return nil, err
		} else if sl == nil {
			return nil, IndexOutOfRangeError
		}
	}
	res := sl.([]interface{})
	if index >= len(res) {
		return nil, IndexOutOfRangeError
	}
       return res, nil
}
```
this can be used by others

**Comment by jhump** [comment]
> I am not able to find any function that returns res as whole

The normal field accessors do this (`GetField`, `GetFieldByNumber`, etc).

https://pkg.go.dev/github.com/jhump/protoreflect/dynamic#Message.TryGetField

**Comment by jhump** [comment]
@krtkvrm, was the above reply sufficient for your needs? Can I close this issue?
