### ISSUE TITLE
how to convert dynamic message to json 

### ISSUE THREAD

**Issue by Khushbukela** [jhump/protoreflect#474]
not able to convert dynamic message to JSON if the dynamic message has any (type and URL) 

md := fd.FindMessage(messageName)
dm := dynamic.NewMessage(md)
err := dm.Unmarshal(protobufMsg)
now how can I convert dynamic message to json . this is the doubt

**Comment by jhump** [comment]
I'm try to understand the question. Are you saying that, in your example, `md` is the message descriptor for `google.protobuf.Any`? Or are you saying that `protobufMsg` is an encoded `google.protobuf.Any`, and you are trying to unmarshal its enclosed data into a dynamic message?

**Comment by Khushbukela** [comment]
my protomsg  containing this field 
![image](https://user-images.githubusercontent.com/88418675/147041969-43deed12-53e2-4c7e-b251-413016adaff4.png)

dynamic message- 
other_properties:<type_url:"example.com/yaddayaddayadda/" value:"serialized" >

**Comment by jhump** [comment]
@Khushbukela, I still don't follow. Can you provide a code example with more context and an actual JSON input example, too? And also say what it is you are seeing vs. what you _expect_ to see? Are you getting an error? Is the unmarshaled value incorrect?

**Comment by hitzhangjie** [comment]
You can just call dm.MarshalJSON or dm.MarshalJSONPB.
