### ISSUE TITLE
protoparse fails to parse custom option with "any" type url value

### ISSUE THREAD

**Issue by codebutler** [jhump/protoreflect#482]
Given proto file like:

```proto
extend google.protobuf.FileOptions {
  optional Aggregate fileopt = 15478479;
}

message Aggregate {
  optional google.protobuf.Any any = 6;
}

option (fileopt) = {
  any {
    [type.googleapis.com/protobuf_unittest.AggregateMessageSetElement] {
      s: 'EmbeddedMessageSetElement'
    }
  }
};
```

This code:

```go
p := &protoparse.Parser{}
fd, err := p.ParseFiles("unittest_custom_options.proto", "test.proto")
if err != nil {
    panic(err)
}
```

Produces this error:

```
panic: unittest_custom_options.proto:387:25: syntax error: unexpected '/', expecting ']'
```

This is supported by `protoc`:
* Unit test fixture: [unittest_custom_options.proto#387](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/unittest_custom_options.proto#L387)
* Implementation: [text_format.cc#L1175](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format.cc#L1175)
* Note that there's special handling of the literal prefix `type.googleapis.com/`: [descriptor.cc#L7653](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.cc#L7653)

**Comment by jhump** [comment]
Ooh, wow, this is a fun one. I had seen that undocumented syntax for `Any` messages in the text format, but definitely did not realize that protoc support it this way.
