### ISSUE TITLE
go\src\github.com\jhump\protoreflect\desc\protoparse\proto.y.go:1110]: constant -9223372036854775808 overflows int

### ISSUE THREAD

**Issue by AndrewHogg** [jhump/protoreflect#49]
While using the latest code to use the Protoparse, I noticed that I am unable to compile due to an overflowing int value. Problem is specific to using GOARCH=386, it works ok on amd64.

**Comment by AndrewHogg** [comment]
Fixed locally by changing line 230 : 
	protolex.Error(fmt.Sprintf("numeric constant %d would underflow (allowed range is %d to %d)", $2, int64(math.MinInt64), int64(math.MaxInt64)))

Would of pushed a branch and a pull request, but lacking permission.

**Comment by jhump** [comment]
@AndrewHogg: Thanks for letting me know! This will be fixed momentarily (#50).

I got an email about a comment on this issue that seems to have been deleted:

> Fixed locally by changing line 230 :
protolex.Error(fmt.Sprintf("numeric constant %d would underflow (allowed range is %d to %d)", $2, int64(math.MinInt64), int64(math.MaxInt64)))
>
> Would of pushed a branch and a pull request, but lacking permission.

For future reference, the typical workflow in open-source is to create a fork, commit your change to a branch in that fork, and then open a pull request against upstream. Here's some more info:
https://help.github.com/articles/fork-a-repo/
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by jhump** [comment]
Resolved with #50

**Comment by AndrewHogg** [comment]
Thanks, I'm discovering a few more issues I'll raise as I figure out whats going on.

**Comment by jhump** [comment]
@AndrewHogg: thanks for taking it for a test drive. I've played around quite a lot on my Macbook Pro, but it sounds like you've got a different dev environment to help shake out very different kinds of bugs. Thanks for your contributions!
