### ISSUE TITLE
dynamic.MarshalJSON - no way to override omission of empty or default value message fields

### ISSUE THREAD

**Issue by pboyer** [jhump/protoreflect#5]
Message definition: 

```
message point {
	double x = 1;
	double y = 2;
	double z = 3;
}
```

Message instantiation: 
```
msg := pointline.Point{ X : 12, Y : -12, Z : 0 } // note Z field is zero
```

Expected output from dynamic.MarshalJSON:
```
{"x":12,"y":-12,"z":0}
```

Got:
```
{"x":12,"y":-12}
```

**Comment by pboyer** [comment]
In this case, it would be nice if you could pass in a custom marshaler with an option for this, e.g. `OmitDefault`.

**Comment by jhump** [comment]
I did see that `jsonpb` had some options like this. I just hadn't gotten a chance to add things like that. I was also wanting to add options so that it doesn't blow if it encounters unknown field names or unknown enum value names.

Thanks for filing this!
