### ISSUE TITLE
"cannot parse invalid wire-format data" error when JSON-marshaling dynamic message containing an Any-type field

### ISSUE THREAD

**Issue by mark-rushakoff** [jhump/protoreflect#507]
I am integrating protoreflect into https://github.com/strangelove-ventures/lens to allow dynamically interacting with remote gRPC servers. We are exposing a JSON-based interface from the command line to do this. The first several services and methods I tried worked great, but then we ran into a difficult-to-debug error on a response message that has an Any field. When we attempt to Marshal it as JSON, we get a `proto: cannot parse invalid wire-format data` error. Marshaling as text is successful, but that format is not useful to consumers of this application.

I made a minimal reproducer at https://github.com/mark-rushakoff/protoreflect-json-marshal-any-repro. The reproducer can be run "online", connecting to the live gRPC server and dynamically resolving the message types, then attempting to JSON-marshal the response. It also has an "offline" mode that uses a locally stored binary protobuf response, with locally defined dynamic messages. The offline mode fails the same way, but hopefully eliminates a misbehaving server as a cause of the failure.

I have separately confirmed that the binary response can be parsed successfully by other tools, such as `protoc --decode_raw` and https://protobuf-decoder.netlify.app/.

I am fairly convinced at this point that this is a bug in protoreflect, but I have certainly not ruled out my own misuse of the library.

I will probably spend some more time trying to debug the issue, and I'll update here if I learn anything helpful.

**Comment by mark-rushakoff** [comment]
I am providing an AnyResolver for the offline case that just returns an empty dynamic message, and for the online case that uses the reflection client to resolve the type from the server.

https://github.com/mark-rushakoff/protoreflect-json-marshal-any-repro/blob/18da946582d9f1b1adbcab263bff8ec60f0ba63e/main.go#L90-L92
https://github.com/mark-rushakoff/protoreflect-json-marshal-any-repro/blob/18da946582d9f1b1adbcab263bff8ec60f0ba63e/main.go#L168-L196

Without the AnyResolver, there is a more helpful `unknown message type` error.

It looks like using the grpcurl library successfully marshals JSON, so I am unblocked. But the invalid wire-format error is still strange and was not helpful in debugging what I did wrong when using protoreflect directly.

**Comment by jhump** [comment]
> I am providing an AnyResolver for the offline case that just returns an empty dynamic message

The actual message type is important here. Is your resolver able to load a message descriptor for the type in question in the offline case?

> But the invalid wire-format error is still strange and was not helpful in debugging what I did wrong when using protoreflect directly.

It would be helpful if you could provide an example of the offending JSON as well as details of the corresponding message descriptor.

**Comment by mark-rushakoff** [comment]
> The actual message type is important here. Is your resolver able to load a message descriptor for the type in question in the offline case?

Yes.

```go
func (r textProposalResolver) Resolve(typeURL string) (proto.Message, error) {
	if typeURL != "/cosmos.gov.v1beta1.TextProposal" {
		panic("textProposalResolver cannot resolve " + typeURL)
	}

	mbTextProposal, err := builder.NewMessage("TextProposal").Build()
	if err != nil {
		panic(fmt.Errorf("failed to build text proposal: %w", err))
	}
	return mbTextProposal.AsProto(), nil
}
```

> It would be helpful if you could provide an example of the offending JSON as well as details of the corresponding message descriptor.

You can run the reproducer in online mode, or grpcurl at the command line works.

```console
$ grpcurl -plaintext osmosis.strange.love:9090 describe cosmos.gov.v1beta1.Proposal
cosmos.gov.v1beta1.Proposal is a message:
message Proposal {
  option (.gogoproto.equal) = true;
  uint64 proposal_id = 1 [(.gogoproto.jsontag) = "id", (.gogoproto.moretags) = "yaml:\id\"];
  .google.protobuf.Any content = 2 [(.cosmos_proto.accepts_interface) = "Content"];
  .cosmos.gov.v1beta1.ProposalStatus status = 3 [(.gogoproto.moretags) = "yaml:\proposal_status\"];
  .cosmos.gov.v1beta1.TallyResult final_tally_result = 4 [(.gogoproto.moretags) = "yaml:\final_tally_result\", (.gogoproto.nullable) = false];
  .google.protobuf.Timestamp submit_time = 5 [(.gogoproto.moretags) = "yaml:\submit_time\", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  .google.protobuf.Timestamp deposit_end_time = 6 [(.gogoproto.moretags) = "yaml:\deposit_end_time\", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  repeated .cosmos.base.v1beta1.Coin total_deposit = 7 [(.gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins", (.gogoproto.moretags) = "yaml:\total_deposit\", (.gogoproto.nullable) = false];
  .google.protobuf.Timestamp voting_start_time = 8 [(.gogoproto.moretags) = "yaml:\voting_start_time\", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
  .google.protobuf.Timestamp voting_end_time = 9 [(.gogoproto.moretags) = "yaml:\voting_end_time\", (.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];
}
```

**Comment by jhump** [comment]
I think I see the problem: this is not correct usage of the API.

The `proto.Message` value should be the actual message type -- not a message descriptor proto. The `builder` package creates descriptors. You would need to go one step further and create a dynamic message using `mbTextProposal`. You could also link in the generated Go package for `cosmos.gov.v1beta1.TextProposal` and just return a message of that type, e.g. `&TextProposal{}`.

However, the message type you are building is always empty. I think that will cause JSON unmarshaling issues unless you are setting the `AllowUnknownFields` property on a `jsonpb.Umarshaler`. If you don't set that field, I would expect an error of some sort upon encountering any field in the JSON content.

Can you provide the full details of the "invalid wire format" error that you receive? Or is there nothing in the error other than that string?

**Comment by jhump** [comment]
> proto: cannot parse invalid wire-format data,

I think this is actually expected. If you have bytes for one message (such as a custom message type) and then try to unmarshal them into another message (such as a descriptor proto), this can happen. The serialized bytes are incompatible between the two messages because they use different/incompatible wire format encoding types for the same field number.
