### ISSUE TITLE
nil pointer dereference in linker.go

### ISSUE THREAD

**Issue by sundbry** [jhump/protoreflect#508]
I was trying to compile the [envoy protobufs](https://github.com/envoyproxy/data-plane-api) using buf-1.3.1 and protoreflect-1.11.1 when the program crashed:

```
$ buf lint
Failure: panic: runtime error: invalid memory address or nil pointer dereference, stack:
goroutine 67 [running]:
runtime/debug.Stack()
	/gnu/store/aiw1716ia4qgwsckcls59sw57dwqr3fg-go-1.17.6/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/bufbuild/buf/private/bufpkg/bufimage/bufimagebuild.getBuildResults.func1.2()
	/tmp/guix-build-buf-1.3.1.drv-0/source/source/private/bufpkg/bufimage/bufimagebuild/builder.go:158 +0x46
panic({0xd00680, 0x1612040})
	/gnu/store/aiw1716ia4qgwsckcls59sw57dwqr3fg-go-1.17.6/lib/go/src/runtime/panic.go:1038 +0x215
github.com/jhump/protoreflect/desc/protoparse.(*linker).createDescriptorPool(0xc02d703720)
	/tmp/guix-build-buf-1.3.1.drv-0/source/go/pkg/mod/github.com/jhump/protoreflect@v1.11.1-0.20220213155251-0c2aedc66cf4/desc/protoparse/linker.go:149 +0x5dd
github.com/jhump/protoreflect/desc/protoparse.(*linker).linkFiles(0xc02d703720)
	/tmp/guix-build-buf-1.3.1.drv-0/source/go/pkg/mod/github.com/jhump/protoreflect@v1.11.1-0.20220213155251-0c2aedc66cf4/desc/protoparse/linker.go:35 +0x33
github.com/jhump/protoreflect/desc/protoparse.Parser.ParseFiles({{0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, 0xc000d0a048, 0x1, 0x0, 0x0, ...}, ...)
	/tmp/guix-build-buf-1.3.1.drv-0/source/go/pkg/mod/github.com/jhump/protoreflect@v1.11.1-0.20220213155251-0c2aedc66cf4/desc/protoparse/parser.go:232 +0x2f6
github.com/bufbuild/buf/private/bufpkg/bufimage/bufimagebuild.getBuildResult({0xf935f0, 0xc0002e85a0}, {0xf9a0a0, 0xc000d09bc0}, {0xc000d90000, 0x0, 0x9a}, 0x0)
	/tmp/guix-build-buf-1.3.1.drv-0/source/source/private/bufpkg/bufimage/bufimagebuild/builder.go:211 +0x250
github.com/bufbuild/buf/private/bufpkg/bufimage/bufimagebuild.getBuildResults.func1()
	/tmp/guix-build-buf-1.3.1.drv-0/source/source/private/bufpkg/bufimage/bufimagebuild/builder.go:162 +0xd1
created by github.com/bufbuild/buf/private/bufpkg/bufimage/bufimagebuild.getBuildResults
	/tmp/guix-build-buf-1.3.1.drv-0/source/source/private/bufpkg/bufimage/bufimagebuild/builder.go:141 +0x7ba
```

The pertinent line for the stack trace is here: https://github.com/jhump/protoreflect/blob/e5b652849f7f16dfb9db81453ec5d2804266750b/desc/protoparse/linker.go#L149

I'm not sure exacty which value is nil. The envoy protobuf repository is pretty complex so it's probably a bit of an Acid test to handle it.

**Comment by jhump** [comment]
Related to/same as bufbuild/buf#1071.

I did a brief review of the code, and I don't think `l.errs` can be nil. So it must be that `getNode` in the parse result is returning a nil interface. That's not supposed to happen -- it should return a special "no source" placeholder node for this sort of case.

I think I have an idea about the cause: I bet there are cases where querying for the AST node for a _synthetic_ descriptor (like the oneofs auto-created for "proto3 optional" fields, and possibly a synthetic map entry message) might do the wrong thing here. I'll add some test cases for these and see if that enables me to reproduce the issue.

**Comment by bufdev** [comment]
I updated `buf` to use this in https://github.com/bufbuild/buf/pull/1072, and am having a weird issue - I basically copied in the test you added here, and this test correctly passes on my local Macbook, but is failing in CI - that might be a red herring, but:

- The test: https://github.com/bufbuild/buf/blob/protoreflect-error/private/bufpkg/bufimage/bufimagebuild/builder_test.go#L276
- The failing CI job (where the `buf build` error does not happen: https://github.com/bufbuild/buf/runs/6054720137?check_suite_focus=true)

To see if this is a mac vs linux thing somehow, I also ran everything within Docker locally, and the test correctly passes, so I have no idea what is going on.

**Comment by bufdev** [comment]
This has been incorporated in buf v1.4.0.
