### ISSUE TITLE
Filed in proto file is defined in lowerscorecase, but (m *Message) MarshalJSON() return a camelcase filed json

### ISSUE THREAD

**Issue by li-ming-lei** [jhump/protoreflect#509]
is there any setting option to change return filed from camelcase to lowerscorecase , the same as i defined in proto file

**Comment by jhump** [comment]
Use the [`MarshalJSONPB`](https://pkg.go.dev/github.com/jhump/protoreflect/dynamic#Message.MarshalJSONPB) method and supply a `jsonpb.Marshaler` whose `OrigName` field is true.

**Comment by li-ming-lei** [comment]
Appreciate for your advice. I sovled it
