### ISSUE TITLE
an int64 value in pb is changed to string when use PbToJson Message.MarshalJSONPB

### ISSUE THREAD

**Issue by li-ming-lei** [jhump/protoreflect#510]

**Comment by jhump** [comment]
I don't see a compelling reason why this dynamic message package should provide different/more JSON marshaling capabilities than the main protobuf runtime. Sorry.

**Comment by weiyinfu** [comment]
> change int64 to int32 instead, or use json.Marshal instead of jsonpb.Marshal.
Some people are using C++ rather than golang.

**Comment by weiyinfu** [comment]
> I don't see a compelling reason why this dynamic message package should provide different/more JSON marshaling capabilities than the main protobuf runtime. Sorry.


I am using C++ in the client. The communication data with the server is JSON. The server-side developer don't want to use protobuffer. But I need a structure definition in the client. So I write proto and generate structure then serialize the structure as string. The server-side cannot parse string to int64. So I need to make some change.

In a word, I use protobuffer as a structure-to-json tool. I don't need ask other people follow the "int64 serialize as string" rule.
