### ISSUE TITLE
protoparse: duplicate symbol already defined as enum value in another proto

### ISSUE THREAD

**Issue by hitzhangjie** [jhump/protoreflect#513]
OS: macOS
jhump/protoreflect version: v1.12.0
go version: 1.16.3

I have written two protos, which under the same folder with the same package directive.

f1.proto:

```
package xxx;

enum Type1 {
    IDC_VAL;
}
```

f2.proto:

```
package xxx;
enum Type2 {
     IDC_VAL;
}
```

When I call protoparse to parse these protos, it reports duplicate symbol IDC_VAL already defined in the other proto.

**Comment by hitzhangjie** [comment]
I found a similar issue: https://github.com/jhump/protoreflect/issues/400.

**Comment by hitzhangjie** [comment]
This may be caused by the protobuf specification: https://github.com/protocolbuffers/protobuf/issues/6912.

**Comment by jhump** [comment]
@hitzhangjie, this is expected and is the same behavior you'll get with `protoc`, whose implementation is the defacto "spec" for the protocol buffers language.

**Comment by ericliu1990** [comment]
Hello @jhump 

the following error was encountered 
`panic: github.com/gogo/protobuf/gogoproto/gogo.proto:22:1: duplicate symbol streams.t.bstream.B: already defined as message in "0"`
when i was using the protobuf below to call function `descs, err := parser.ParseFiles()`

```
syntax = "proto3";
package streams.t.bstream;

option go_package = "github.com/go/streams/t/bstream";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "streams/coban/stream_info.proto";
import "streams/coban/options/v1/pii.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;
option (gogoproto.equal_all) = true;


message bBag {
  repeated B entries = 1;
}

message B {
  Info Info = 1;
}

message Info {
  int64 ID = 1;
  string Code = 2;
  repeated LocationInfo locationHistory = 3;
  int64 timeSaved = 4;
}
```

**Comment by jhump** [comment]
@ericliu1990, does this file import itself (see line 6)? If this is the file you are trying to parse, the error message appears to suggest that the import at line 6 tries to redefine the symbol `B` (which is also defined in the above file, next to the last element).
