### ISSUE TITLE
protoprint: printable unicode characters >= code point 0080 are not preserved

### ISSUE THREAD

**Issue by xgtcode** [jhump/protoreflect#527]
hi, I encountered an error while using function `printer.PrintProtoToString`
here are operating steps:
- step 1: use function `parser.parseprotofile` to parse .proto file to fileDescriptor 
- step 2: modify some field options
- step 3: use function `printer.PrintProtoFile` to output modified fileDescriptor into file
the proto file contains some Chinese characters, but the output isn't as expected:
` string key = 1 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {description:"这个是key值" required:"true"}];`
`string key = 1 [
      (grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
        description: "\350\277\231\344\270\252\346\230\257key\345\200\274"
        required: "true"
      }
    ];`
how to solve it ？

**Comment by jhump** [comment]
@xgtcode, it looks like it was doing a naive byte-based encoding to string literal and considering everything outside the ASCII 7-bit range unprintable, thus other code points being encoded as a sequence of octal escapes.

It should be fixed by #529.
