### ISSUE TITLE
how to marshal json for nested message

### ISSUE THREAD

**Issue by tonglin96** [jhump/protoreflect#538]
my code: 
```
resp := dynamic.NewMessage(v.Resp)
resp.MarshalJSONPB(&jsonpb.Marshaler{OrigName: true, EmitDefaults: true})
```

i got: `{"history_list":[],"total":"0"}`
but i want to got like this for nested meesage: ``{"history_list":[{"id": 0, "name": ""}],"total":"0"}``

**Comment by jhump** [comment]
The `history_list` field in the example is empty, so it renders as an empty JSON array. This is expected.

It looks like what you are trying to do is already implemented in [`grpcurl.MakeTemplate`](https://pkg.go.dev/github.com/fullstorydev/grpcurl#MakeTemplate)

```diff
+resp := grpcurl.MakeTemplate(v.Resp)
+(&jsonpb.Marshaler{OrigName: true, EmitDefaults: true}).MarshalToString(resp)
-resp := dynamic.NewMessage(v.Resp)
-resp.MarshalJSONPB(&jsonpb.Marshaler{OrigName: true, EmitDefaults: true})
```

**Comment by tonglin96** [comment]
> The `history_list` field in the example is empty, so it renders as an empty JSON array. This is expected. If you want it to render the list as having a single element (an empty message), you have to add an element to that field.
> 
> But it looks like what you are trying to do might already be implemented in [`grpcurl.MakeTemplate`](https://pkg.go.dev/github.com/fullstorydev/grpcurl#MakeTemplate)
> 
> ```diff
> +resp := grpcurl.MakeTemplate(v.Resp)
> +(&jsonpb.Marshaler{OrigName: true, EmitDefaults: true}).MarshalToString(resp)
> -resp := dynamic.NewMessage(v.Resp)
> -resp.MarshalJSONPB(&jsonpb.Marshaler{OrigName: true, EmitDefaults: true})
> ```

ok, thanks
