### ISSUE TITLE
Calling client.AllExtensionNumbersForType when no extensions exist returns an error

### ISSUE THREAD

**Issue by nihar-aalyria** [jhump/protoreflect#558]
# Overview

I have a `grpcreflect.Client` on which I am calling `AllExtensionNumbersForType(typeName)`. The type on which I am calling it refers to a very simple proto, resembling:

```
package foo;

message Bar {
  optional int baz = 1;

  extensions 100 to max;
}
```

No extensions to `Bar` currently exist. Strangely, calling [`AllExtensionNumbersForType("foo.Bar")`](https://github.com/jhump/protoreflect/blob/bc899ec1d2c0fafef8a3bc8eaccfe6031badb354/grpcreflect/client.go#L433) is returning an error. 

# Hypothesis
I wonder if part of the issue could be [doSendLocked()](https://github.com/jhump/protoreflect/blob/5556ec8c531af3af0c5bc10d6287ccc4ad3b33c1/grpcreflect/client.go#L514)'s handling of `io.EOF` errors. This function calls `cr.stream.Recv()`, which calls [refv1alpha.ServerReflection_ServerReflectionInfoClient.Recv()](https://github.com/grpc/grpc-go/blob/v1.54.0/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go#L83), which calls [grpc.ClientStream.RecvMsg()](https://github.com/grpc/grpc-go/blob/v1.54.0/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go#L85). According to the [comments for grpc.ClientStream.RecvMsg()](https://pkg.go.dev/google.golang.org/grpc#ClientStream), when a stream terminates normally, an error of `io.EOF` is returned. 

So, I wonder if there needs to be any special handling in doSendLocked() for this case where no extensions exist. In this case, `cr.stream.Recv()` is expected to return `io.EOF` and this does not indicate an error but rather the end of an empty stream. My intuition would be that doSendLocked() returns an empty response and a nil error, instead of the current behavior of returning a nil response and the error.

Apologies if I've misunderstood -- definitely open to suggestions and discussion. Thank you!

**Comment by jhump** [comment]
@nihar-aalyria, I'm afraid EOF is not the issue. If that is what you are seeing, then this is an actual error. The way the server is _supposed_ to reply is to send a response message in reply to the request for extension numbers. The reflection protocol is a bidi stream, so the client sends requests as individual messages on the stream and then, in the same order as requests were sent, receives replies, one to one.

If you have not confirmed that the server is sending an EOF, then I suspect that the _server_ is sending back an error. In responding to an ["all extension numbers" request](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L47-L55), the server can send back either an ["all extension numbers" reply](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L86-L87) or an [error reply](https://github.com/grpc/grpc/blob/master/src/proto/grpc/reflection/v1alpha/reflection.proto#L92-L93).

It would be easier to hypothesize on what is happening if you include some details on the error you are seeing -- like the actual error code and message.

**Comment by nihar-aalyria** [comment]
Thank you for the quick reply, and apologies for the late response! I'll look into the error code and message, and re-open this issue if I have further details. Thanks!
