### ISSUE TITLE
Any method for setting nested MessageKind field

### ISSUE THREAD

**Issue by HugoNgai** [jhump/protoreflect#561]
Hi master, I wonder if there is any way for setting a field as A MessageKind.

For example,  

`message Example {
  string A = 1;
  string B = 2;
  NestedFieldA C = 3;
}

message NestedFieldA {
  string  D = 1;
  string E = 2;
  NestedFieldB F = 3;
}

message NestedFieldB {
  string G = 4;
}`

json type bytes:
`var test := {
	"A": "test",
	"B": "test",
	"C": null
}`

- Firstly, I create a dynamic Message 
`msg  := dynamic.NewMessage(mds)`
- Unmarshal Json to msg
`msg.UnmarshalJSON(test)`

how can I dynamically set some value to `NestedFieldA` C or `NestedFieldB` F using methed msg.TrySetField?

**Comment by jhump** [comment]
> Is there and method like Mutable in this repo?

@HugoNgai, no. In fact, you should just use the `dynamicpb` package. The `dynamic` package in this repo is effectively deprecated. See the blurb at the top of this repo's [README](https://github.com/jhump/protoreflect/blob/v1/README.md#%EF%B8%8F-note). You can get a preview of v2 [here](https://github.com/jhump/protoreflect/tree/v2), and you'll see there will no longer be a `dynamic` package.

**Comment by HugoNgai** [comment]
@jhump 👌 thx！
