### ISSUE TITLE
String escaping in protoprint is wrong

### ISSUE THREAD

**Issue by japersik** [jhump/protoreflect#579]
This case [(link)](https://github.com/jhump/protoreflect/blob/3839451e1677ae9870ddac6e21dd2db4f3f14a7d/desc/protoprint/print.go#L2064
)
```
		case '"':
			b.WriteString("\\")
```
must be 
```
		case '"':
			b.WriteString("\\\"")
```
 otherwise, options with a string value are printed incorrectly
example:
```
option (._mt_string_option) = "Some \"string value\"";
```
will be converted to 
```
option (._mt_string_option) = "Some \string value\";
```
and it is an incorrect protobuf file

**Comment by jhump** [comment]
Fixed in #580. Thanks for the fix, @japersik!!
