### ISSUE TITLE
Upgrade protocompile to v0.7.0

### ISSUE THREAD

**Issue by Shnitzelil** [jhump/protoreflect#585]
Hi,
Please upgrade github.com/bufbuild/protocompile to v0.7.0.

Thanks

**Comment by jhump** [comment]
This will have to hold off until a v0.7.1 version is released.
See https://github.com/bufbuild/protocompile/pull/217

**Comment by jhump** [comment]
You should now be able to upgrade to v1.15.4.

**Comment by Shnitzelil** [comment]
> You should now be able to upgrade to v1.15.4.

Thanks for the quick fix :)
