### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by CodingJzy** [jhump/protoreflect#587]
# code
```go
package main

import (
	"fmt"
	"github.com/jhump/protoreflect/desc/protoparse"
	"log"
)

func parse() {
	var parser protoparse.Parser
	files := "./hello-world.pro111to"
	descriptors, err := parser.ParseFiles(files)
	if err != nil {
		log.Println(err)
		return
	}
	fmt.Println(descriptors)
}

func main() {

	fmt.Println("xxx")
	//parse()
}

```

# error
![image](https://github.com/jhump/protoreflect/assets/44855157/8af4aea3-5582-4cfa-9db1-9a6761a6b3da)

**Comment by CodingJzy** [comment]
i use your protoreflect pkg , display the error.
if i not import the "github.com/jhump/protoreflect/desc/protoparse", no error

**Comment by jhump** [comment]
@CodingJzy, sorry, but it looks like something is wrong with your Go toolchain. What does `go version` report?

**Comment by jhump** [comment]
@CodingJzy, any more info on this? Did you get it working? I am not able to reproduce and, as mentioned in previous comment, suspect something weird in your Go toolchain.
