### ISSUE TITLE
Regression upgrading from v1.14.1 to v1.15.4: extensions are resolved recursively instead of non-recursively

### ISSUE THREAD

**Issue by stapelberg** [jhump/protoreflect#589]
I noticed a behavioral difference when upgrading from protoreflect v1.14.1 to protoreflect v1.15.4.

When using protoprint to generate a .proto file, a few `import` lines are missing compared to before. The affected imports are other .proto files that declare option extensions.

I tracked this down to `desc/builder/resolver.go:resolveTypesInOptions` thinking the extension is already known and therefore not adding a dependency.

This, in turn, is caused by the following difference:

In v1.14.1, extensions are added non-recursively (`recursive == false`):

* https://github.com/jhump/protoreflect/blob/0facb742c9dcbc99667de77a4b74b842f9aa0bb3/desc/builder/resolver.go#L31
* https://github.com/jhump/protoreflect/blob/0facb742c9dcbc99667de77a4b74b842f9aa0bb3/dynamic/extension_registry.go#L71-L86

But in v1.15.4, extensions are added recursively (`publicImportsOnly == false`, which is equivalent to `recursive == true`):

* https://github.com/jhump/protoreflect/blob/f139a6debe4ec67cddb8e11df35b8a1934203c68/desc/builder/resolver.go#L36
* https://github.com/jhump/protoreflect/blob/f139a6debe4ec67cddb8e11df35b8a1934203c68/desc/internal/registry.go#L9-L25

I hope this is enough information to work with. Let me know if you can’t make progress without a proper standalone reproducer, though extracting one will take me a couple of days I expect…

**Comment by jhump** [comment]
@stapelberg, thanks for this report! I don't need a full repro case. I see the issue. Thanks for debugging it so thoroughly and providing those details!

I'm opening a pull request with a fix now.
