### ISSUE TITLE
Methods for Get / Set by Name

### ISSUE THREAD

**Issue by AndrewHogg** [jhump/protoreflect#63]
I'm noticing a lot of repetition in my code due to wanting to set a field by name, resulting in this pattern appearing repeatedly:
   myMessage.SetField(myMessage.FindFieldDescriptorByName("myfield"), myValue)

I've added some helper methods which changes the code to a neater:
   myMessage.SetFieldByName("myfield", myvalue)

Example method added
var UnknownFieldNameError = errors.New("Unknown field name")
...
func (m *Message) SetFieldByName(name string, val interface{}) {
	if err := m.TrySetFieldByName(name, val); err != nil {
		panic(err.Error())
	}
}

func (m *Message) TrySetFieldByName(name string, val interface{}) error {
	fd := m.md.FindFieldByName(name)
	if fd == nil {
		return UnknownFieldNameError
	}
	return m.setField(fd, val)
}

I'm happy to extend that ByName functionality to the other methods (GetField, HasField, Clearfield etc and submit a PR, just checking if you agree with adding it before I do the work + tests.

**Comment by jhump** [comment]
@AndrewHogg, that sounds good. I will happily accept a patch if you can apply it to all methods (e.g. all methods that already have a `*ByNumber` form).

**Comment by AndrewHogg** [comment]
PR created for the methods being added : https://github.com/jhump/protoreflect/pull/64, will need a good review

**Comment by jhump** [comment]
Resolved by #64
