### ISSUE TITLE
Protoparse fails when given a proto3 file with maps

### ISSUE THREAD

**Issue by jkinkead** [jhump/protoreflect#69]
The protoparse library fails when validating a proto3 file with a map field, when trying to validate the synthesized `{FieldName}Entry` message:
```
field FieldNameEntry.key: field has label LABEL_OPTIONAL, but proto3 should omit labels other than 'repeated'
```
You can repro this by adding a line to [internal/testprotos/desc_test_proto3.proto](internal/testprotos/desc_test_proto3.proto) like:
```proto
// Inserted after "snafu", or in any message.
map<string, string> fieldName = 5;
```
and then running the parser unit tests.

It looks like fixing would involve passing the `map_entry` value from [MessageOptions](https://github.com/google/protobuf/blob/c4f59dcc5c13debc572154c8f636b8a9361aacde/src/google/protobuf/descriptor.proto#L482) down to the [validateField function](https://github.com/jhump/protoreflect/blob/8083885e1b19048ab0cd2b12dae8405050864ff1/desc/protoparse/parser.go#L925).

I'm happy to make that change if you think it's reasonable.

**Comment by jkinkead** [comment]
I have a fix that appears to work, but fails during unit test validation; I can't get `make_protos.sh` to work correctly. If you have any pointers, I'm happy to get this working and submit a patch!

**Comment by jhump** [comment]
@jkinkead, sorry you couldn't get `make_protos.sh` to work. Any hints on what part of the script was failing? If you can make some changes to get it to work in your environment, I'll take a patch.

I just merged a small change that appears to address it. Let me know if it looks anything like your fix and re-open this issue if it doesn't address it for you.

**Comment by jkinkead** [comment]
Awesome, I confirmed that fix works. Your solution is cleaner than mine was, as well. :)

`make_protos.sh` was giving me errors because it couldn't find `google/protobuf/descriptor.proto`:
```
google/protobuf/descriptor.proto: File not found.
desc_test_options.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
desc_test_options.proto:9:8: "google.protobuf.MessageOptions" is not defined.
desc_test_options.proto:13:8: "google.protobuf.FieldOptions" is not defined.
desc_test_options.proto: "google.protobuf.FieldOptions" is not defined.
desc_test_options.proto:18:8: "google.protobuf.EnumOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumOptions" is not defined.
desc_test_options.proto:26:8: "google.protobuf.EnumValueOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumValueOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumValueOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumValueOptions" is not defined.
desc_test_options.proto: "google.protobuf.EnumValueOptions" is not defined.
desc_test_options.proto:34:8: "google.protobuf.ServiceOptions" is not defined.
desc_test_options.proto: "google.protobuf.ServiceOptions" is not defined.
desc_test_options.proto:39:8: "google.protobuf.MethodOptions" is not defined.
desc_test_options.proto: "google.protobuf.MethodOptions" is not defined.
```
It's possible that I haven't installed protoc correctly (IIRC I used homebrew), or I'm missing a key dependency / path item.

**Comment by jhump** [comment]
protoc installations should include these proto files. Typically, they are installed alongside the protoc binary (like in an `include` folder that is a sibling of protoc or, if protoc is in a `bin` folder, the `include` folder is sibling of that).

I have a custom protoc install at the moment, built from source, and it works. You might try that (clone the protobuf repo and build the binary -- which will end up in the `src` directory of the repo).
