### ISSUE TITLE
Error messages can be overly opaque

### ISSUE THREAD

**Issue by jhump** [jhump/protoreflect#82]
The current pattern through out the code in this repo is to propagate error values directly, without much in the way of transforming/wrapping.

The exception to this is the `protoparse` package, which now provides useful context by attaching locations in source code to each error message. But the `desc` and `dynamic` packages can provide very hard-to-decipher errors -- like when something happens deep in the bowels during de-serialization.

For example, if an error occurs that is related to data types/integrity, the message often lacks necessary context. Even if it indicates a field name, that is often insufficient since it could be working in a deeply nested message, and the field name alone provides little information for a user to act on.

I'd like to take a stab at re-doing the error propagation behavior throughout most of this repo to instead use the [github.com/pkg/errors](https://github.com/pkg/errors) package for wrapping/chaining errors and providing additional context. That way, errors returned to user code have more context to assist with understanding and resolving those errors.

**Comment by sonatard** [comment]
Standard library will be supported wrap error from Go 1.13.

See https://go.googlesource.com/proposal/+/master/design/29934-error-values.md
https://github.com/golang/go/wiki/ErrorValueFAQ

Now we can try wrap error using xerrors package.
https://godoc.org/golang.org/x/xerrors

**Comment by jhump** [comment]
This is almost exclusively a problem with the `desc` package, when building a rich descriptor from protos. The other packages don't generate deep callstacks, where an error could occur many frames from the caller (and thus need more context to understand).

Now that the new protobuf runtime includes descriptor functionality, there's not much reason to audit and improve error handling in this package. (In fact, I intend to soon re-write the `desc` package so its `Descriptor` types are just wrappers around the `Descriptor` types in `google.golang.org/protobuf/reflect/protoreflect`.)
