### ISSUE TITLE
Protoparse fails when parent package types are used without qualification

### ISSUE THREAD

**Issue by jkinkead** [jhump/protoreflect#96]
Proto files let you refer to messages defined in a parent package without having to qualify the message.

For example, if you have a `foo.proto` file like:
```proto
syntax = "proto3";
package foo;

message ParentMessage {
  string foo = 1;
};
```
You can refer to `ParentMessage` without using a package qualifier in a `pkg/bar.proto` file like:
```proto
syntax = "proto3";
package foo.pkg;

message ChildMessage {
  // No qualification needed here!
  ParentMessage msg = 1;
};
```
The proto parser will fail with a message like `unknown type ParentMessage`, while `protoc` will happily resolve this symbol.

**Comment by jkinkead** [comment]
I feel like a loop up through package prefixes [here](https://github.com/jhump/protoreflect/blob/2cc88f9317cd53b4784ab5e07dd321b162a12eb4/desc/protoparse/linker.go#L518-L533) would be the right choice? Let me know if you'd like help, and I could poke around at implementing.

**Comment by jhump** [comment]
Looks like I got to addressing this sooner than I thought this morning :)

**Comment by jhump** [comment]
@jkinkead, mind taking this change for a spin? (I was lazy and didn't add a new test case for it. I'll remedy that omission later.)

**Comment by jkinkead** [comment]
Awesome, thanks! I confirmed that this works with my test service ([PredictionService from TensorFlow](https://github.com/tensorflow/serving/blob/03df9f3078d01ca820eb0d077ddd2814a331c1dc/tensorflow_serving/apis/prediction_service.proto)).
